'use strict';
/*************************************************\
generated from arsdk-xml/xml/*.xml
generated by utils/convertSDK.js
generated on : 2/20/2017, 8:59:08 PM
\**************************************************/
const projects={
  "jpsumo": {
    "info": {
      "tagType": "project",
      "name": "jpsumo",
      "id": 3
    },
    "details": "All commands specific to the Jumping Sumo.",
    "Piloting": {
      "info": {
        "tagType": "class",
        "name": "Piloting",
        "id": 0
      },
      "details": "All commands related to piloting the JumpingSumo",
      "PCMD": {
        "info": {
          "tagType": "cmd",
          "name": "PCMD",
          "id": 0,
          "buffer": "NON_ACK"
        },
        "details": "Ask the JS speed and turn ratio.",
        "flag": {
          "info": {
            "tagType": "arg",
            "name": "flag",
            "type": "u8",
            "id": 0,
            "bytes": 1
          },
          "details": "Boolean for \"touch screen\".",
          "lookup": {},
          "value": null
        },
        "speed": {
          "info": {
            "tagType": "arg",
            "name": "speed",
            "type": "i8",
            "id": 1,
            "bytes": 1
          },
          "details": "Speed value [_100_100].",
          "lookup": {},
          "value": null
        },
        "turn": {
          "info": {
            "tagType": "arg",
            "name": "turn",
            "type": "i8",
            "id": 2,
            "bytes": 1
          },
          "details": "Turn value. [_100_100]",
          "lookup": {},
          "value": null
        },
        "lookup": {
          "0": "flag",
          "1": "speed",
          "2": "turn"
        }
      },
      "Posture": {
        "info": {
          "tagType": "cmd",
          "name": "Posture",
          "id": 1
        },
        "details": "Request a posture",
        "type": {
          "info": {
            "tagType": "arg",
            "name": "type",
            "type": "enum",
            "id": 0,
            "bytes": 4
          },
          "details": "Type of Posture",
          "standing": {
            "info": {
              "tagType": "enum",
              "name": "standing",
              "id": 0
            },
            "details": "Standing type",
            "lookup": {}
          },
          "jumper": {
            "info": {
              "tagType": "enum",
              "name": "jumper",
              "id": 1
            },
            "details": "Jumper type",
            "lookup": {}
          },
          "kicker": {
            "info": {
              "tagType": "enum",
              "name": "kicker",
              "id": 2
            },
            "details": "Kicker type",
            "lookup": {}
          },
          "lookup": {
            "0": "standing",
            "1": "jumper",
            "2": "kicker"
          },
          "value": null
        },
        "lookup": {
          "0": "type"
        }
      },
      "addCapOffset": {
        "info": {
          "tagType": "cmd",
          "name": "addCapOffset",
          "id": 2
        },
        "details": "Add the specified offset to the current cap.",
        "offset": {
          "info": {
            "tagType": "arg",
            "name": "offset",
            "type": "float",
            "id": 0,
            "bytes": 4
          },
          "details": "Offset value in radians.",
          "lookup": {},
          "value": null
        },
        "lookup": {
          "0": "offset"
        }
      },
      "lookup": {
        "0": "PCMD",
        "1": "Posture",
        "2": "addCapOffset"
      }
    },
    "PilotingState": {
      "info": {
        "tagType": "class",
        "name": "PilotingState",
        "id": 1
      },
      "details": "Animations state from JS.",
      "PostureChanged": {
        "info": {
          "tagType": "cmd",
          "name": "PostureChanged",
          "id": 0
        },
        "details": "State of posture changed.",
        "state": {
          "info": {
            "tagType": "arg",
            "name": "state",
            "type": "enum",
            "id": 0,
            "bytes": 4
          },
          "details": "State of posture",
          "standing": {
            "info": {
              "tagType": "enum",
              "name": "standing",
              "id": 0
            },
            "details": "Standing state",
            "lookup": {}
          },
          "jumper": {
            "info": {
              "tagType": "enum",
              "name": "jumper",
              "id": 1
            },
            "details": "Jumper state",
            "lookup": {}
          },
          "kicker": {
            "info": {
              "tagType": "enum",
              "name": "kicker",
              "id": 2
            },
            "details": "Kicker state",
            "lookup": {}
          },
          "stuck": {
            "info": {
              "tagType": "enum",
              "name": "stuck",
              "id": 3
            },
            "details": "Stuck state",
            "lookup": {}
          },
          "unknown": {
            "info": {
              "tagType": "enum",
              "name": "unknown",
              "id": 4
            },
            "details": "Unknown state",
            "lookup": {}
          },
          "lookup": {
            "0": "standing",
            "1": "jumper",
            "2": "kicker",
            "3": "stuck",
            "4": "unknown"
          },
          "value": null
        },
        "lookup": {
          "0": "state"
        }
      },
      "AlertStateChanged": {
        "info": {
          "tagType": "cmd",
          "name": "AlertStateChanged",
          "id": 1
        },
        "details": "JS alert state changed",
        "state": {
          "info": {
            "tagType": "arg",
            "name": "state",
            "type": "enum",
            "id": 0,
            "bytes": 4
          },
          "details": "JS alert state",
          "none": {
            "info": {
              "tagType": "enum",
              "name": "none",
              "id": 0
            },
            "details": "No alert",
            "lookup": {}
          },
          "critical_battery": {
            "info": {
              "tagType": "enum",
              "name": "critical_battery",
              "id": 1
            },
            "details": "Critical battery alert",
            "lookup": {}
          },
          "low_battery": {
            "info": {
              "tagType": "enum",
              "name": "low_battery",
              "id": 2
            },
            "details": "Low battery alert",
            "lookup": {}
          },
          "lookup": {
            "0": "none",
            "1": "critical_battery",
            "2": "low_battery"
          },
          "value": null
        },
        "lookup": {
          "0": "state"
        }
      },
      "SpeedChanged": {
        "info": {
          "tagType": "cmd",
          "name": "SpeedChanged",
          "id": 2
        },
        "details": "Notification sent when JS speed changes.",
        "speed": {
          "info": {
            "tagType": "arg",
            "name": "speed",
            "type": "i8",
            "id": 0,
            "bytes": 1
          },
          "details": "Speed command applied to motors in range [_100;100].",
          "lookup": {},
          "value": null
        },
        "realSpeed": {
          "info": {
            "tagType": "arg",
            "name": "realSpeed",
            "type": "i16",
            "id": 1,
            "bytes": 2
          },
          "details": "Actual real_world speed in cm/s. Value _32768 returned if not available.",
          "lookup": {},
          "value": null
        },
        "lookup": {
          "0": "speed",
          "1": "realSpeed"
        }
      },
      "lookup": {
        "0": "PostureChanged",
        "1": "AlertStateChanged",
        "2": "SpeedChanged"
      }
    },
    "Animations": {
      "info": {
        "tagType": "class",
        "name": "Animations",
        "id": 2
      },
      "details": "Animation commands",
      "JumpStop": {
        "info": {
          "tagType": "cmd",
          "name": "JumpStop",
          "id": 0,
          "buffer": "HIGH_PRIO",
          "timeout": "RETRY"
        },
        "details": "Stop jump, emergency jump stop, stop jump motor and stay there.",
        "lookup": {}
      },
      "JumpCancel": {
        "info": {
          "tagType": "cmd",
          "name": "JumpCancel",
          "id": 1
        },
        "details": "Cancel jump and come back to previous state (if possible).",
        "lookup": {}
      },
      "JumpLoad": {
        "info": {
          "tagType": "cmd",
          "name": "JumpLoad",
          "id": 2
        },
        "details": "Request jump loading",
        "lookup": {}
      },
      "Jump": {
        "info": {
          "tagType": "cmd",
          "name": "Jump",
          "id": 3
        },
        "details": "Request a jump",
        "type": {
          "info": {
            "tagType": "arg",
            "name": "type",
            "type": "enum",
            "id": 0,
            "bytes": 4
          },
          "details": "Type of jump",
          "long": {
            "info": {
              "tagType": "enum",
              "name": "long",
              "id": 0
            },
            "details": "Long jump.",
            "lookup": {}
          },
          "high": {
            "info": {
              "tagType": "enum",
              "name": "high",
              "id": 1
            },
            "details": "High jump",
            "lookup": {}
          },
          "lookup": {
            "0": "long",
            "1": "high"
          },
          "value": null
        },
        "lookup": {
          "0": "type"
        }
      },
      "SimpleAnimation": {
        "info": {
          "tagType": "cmd",
          "name": "SimpleAnimation",
          "id": 4
        },
        "details": "Play a parameterless animation.",
        "id": {
          "info": {
            "tagType": "arg",
            "name": "id",
            "type": "enum",
            "id": 0,
            "bytes": 4
          },
          "details": "Animation ID.",
          "stop": {
            "info": {
              "tagType": "enum",
              "name": "stop",
              "id": 0
            },
            "details": "Stop ongoing animation.",
            "lookup": {}
          },
          "spin": {
            "info": {
              "tagType": "enum",
              "name": "spin",
              "id": 1
            },
            "details": "Start a spin animation.",
            "lookup": {}
          },
          "tap": {
            "info": {
              "tagType": "enum",
              "name": "tap",
              "id": 2
            },
            "details": "Start a tap animation.",
            "lookup": {}
          },
          "slowshake": {
            "info": {
              "tagType": "enum",
              "name": "slowshake",
              "id": 3
            },
            "details": "Start a slow shake animation.",
            "lookup": {}
          },
          "metronome": {
            "info": {
              "tagType": "enum",
              "name": "metronome",
              "id": 4
            },
            "details": "Start a Metronome animation.",
            "lookup": {}
          },
          "ondulation": {
            "info": {
              "tagType": "enum",
              "name": "ondulation",
              "id": 5
            },
            "details": "Start a standing dance animation.",
            "lookup": {}
          },
          "spinjump": {
            "info": {
              "tagType": "enum",
              "name": "spinjump",
              "id": 6
            },
            "details": "Start a spin jump animation.",
            "lookup": {}
          },
          "spintoposture": {
            "info": {
              "tagType": "enum",
              "name": "spintoposture",
              "id": 7
            },
            "details": "Start a spin that end in standing posture, or in jumper if it was standing animation.",
            "lookup": {}
          },
          "spiral": {
            "info": {
              "tagType": "enum",
              "name": "spiral",
              "id": 8
            },
            "details": "Start a spiral animation.",
            "lookup": {}
          },
          "slalom": {
            "info": {
              "tagType": "enum",
              "name": "slalom",
              "id": 9
            },
            "details": "Start a slalom animation.",
            "lookup": {}
          },
          "lookup": {
            "0": "stop",
            "1": "spin",
            "2": "tap",
            "3": "slowshake",
            "4": "metronome",
            "5": "ondulation",
            "6": "spinjump",
            "7": "spintoposture",
            "8": "spiral",
            "9": "slalom"
          },
          "value": null
        },
        "lookup": {
          "0": "id"
        }
      },
      "lookup": {
        "0": "JumpStop",
        "1": "JumpCancel",
        "2": "JumpLoad",
        "3": "Jump",
        "4": "SimpleAnimation"
      }
    },
    "AnimationsState": {
      "info": {
        "tagType": "class",
        "name": "AnimationsState",
        "id": 3
      },
      "details": "Animations state from JS.",
      "JumpLoadChanged": {
        "info": {
          "tagType": "cmd",
          "name": "JumpLoadChanged",
          "id": 0
        },
        "details": "State of jump load changed",
        "state": {
          "info": {
            "tagType": "arg",
            "name": "state",
            "type": "enum",
            "id": 0,
            "bytes": 4
          },
          "details": "State of jump load",
          "unknown": {
            "info": {
              "tagType": "enum",
              "name": "unknown",
              "id": 0
            },
            "details": "Unknown state (obsolete).",
            "lookup": {}
          },
          "unloaded": {
            "info": {
              "tagType": "enum",
              "name": "unloaded",
              "id": 1
            },
            "details": "Unloaded state.",
            "lookup": {}
          },
          "loaded": {
            "info": {
              "tagType": "enum",
              "name": "loaded",
              "id": 2
            },
            "details": "Loaded state.",
            "lookup": {}
          },
          "busy": {
            "info": {
              "tagType": "enum",
              "name": "busy",
              "id": 3
            },
            "details": "Unknown state (obsolete).",
            "lookup": {}
          },
          "low_battery_unloaded": {
            "info": {
              "tagType": "enum",
              "name": "low_battery_unloaded",
              "id": 4
            },
            "details": "Unloaded state and low battery.",
            "lookup": {}
          },
          "low_battery_loaded": {
            "info": {
              "tagType": "enum",
              "name": "low_battery_loaded",
              "id": 5
            },
            "details": "Loaded state and low battery.",
            "lookup": {}
          },
          "lookup": {
            "0": "unknown",
            "1": "unloaded",
            "2": "loaded",
            "3": "busy",
            "4": "low_battery_unloaded",
            "5": "low_battery_loaded"
          },
          "value": null
        },
        "lookup": {
          "0": "state"
        }
      },
      "JumpTypeChanged": {
        "info": {
          "tagType": "cmd",
          "name": "JumpTypeChanged",
          "id": 1
        },
        "details": "State of jump type changed.",
        "state": {
          "info": {
            "tagType": "arg",
            "name": "state",
            "type": "enum",
            "id": 0,
            "bytes": 4
          },
          "details": "State of jump type.",
          "none": {
            "info": {
              "tagType": "enum",
              "name": "none",
              "id": 0
            },
            "details": "None.",
            "lookup": {}
          },
          "long": {
            "info": {
              "tagType": "enum",
              "name": "long",
              "id": 1
            },
            "details": "Long jump type.",
            "lookup": {}
          },
          "high": {
            "info": {
              "tagType": "enum",
              "name": "high",
              "id": 2
            },
            "details": "High jump type.",
            "lookup": {}
          },
          "lookup": {
            "0": "none",
            "1": "long",
            "2": "high"
          },
          "value": null
        },
        "lookup": {
          "0": "state"
        }
      },
      "JumpMotorProblemChanged": {
        "info": {
          "tagType": "cmd",
          "name": "JumpMotorProblemChanged",
          "id": 2
        },
        "details": "State about the jump motor problem",
        "error": {
          "info": {
            "tagType": "arg",
            "name": "error",
            "type": "enum",
            "id": 0,
            "bytes": 4
          },
          "details": "Enum describing the problem of the motor",
          "none": {
            "info": {
              "tagType": "enum",
              "name": "none",
              "id": 0
            },
            "details": "None.",
            "lookup": {}
          },
          "blocked": {
            "info": {
              "tagType": "enum",
              "name": "blocked",
              "id": 1
            },
            "details": "Motor blocked",
            "lookup": {}
          },
          "over_heated": {
            "info": {
              "tagType": "enum",
              "name": "over_heated",
              "id": 2
            },
            "details": "Motor over heated",
            "lookup": {}
          },
          "lookup": {
            "0": "none",
            "1": "blocked",
            "2": "over_heated"
          },
          "value": null
        },
        "lookup": {
          "0": "error"
        }
      },
      "lookup": {
        "0": "JumpLoadChanged",
        "1": "JumpTypeChanged",
        "2": "JumpMotorProblemChanged"
      }
    },
    "SettingsState": {
      "info": {
        "tagType": "class",
        "name": "SettingsState",
        "id": 5
      },
      "details": "Settings state from product",
      "ProductGPSVersionChanged": {
        "info": {
          "tagType": "cmd",
          "name": "ProductGPSVersionChanged",
          "id": 0
        },
        "details": "@deprecated Product GPS versions",
        "software": {
          "info": {
            "tagType": "arg",
            "name": "software",
            "type": "string",
            "id": 0,
            "bytes": 1
          },
          "details": "Product GPS software version",
          "lookup": {},
          "value": null
        },
        "hardware": {
          "info": {
            "tagType": "arg",
            "name": "hardware",
            "type": "string",
            "id": 1,
            "bytes": 1
          },
          "details": "Product GPS hardware version",
          "lookup": {},
          "value": null
        },
        "lookup": {
          "0": "software",
          "1": "hardware"
        }
      },
      "lookup": {
        "0": "ProductGPSVersionChanged"
      }
    },
    "MediaRecord": {
      "info": {
        "tagType": "class",
        "name": "MediaRecord",
        "id": 6
      },
      "details": "Media recording management",
      "Picture": {
        "info": {
          "tagType": "cmd",
          "name": "Picture",
          "id": 0
        },
        "details": "@deprecated Take picture",
        "mass_storage_id": {
          "info": {
            "tagType": "arg",
            "name": "mass_storage_id",
            "type": "u8",
            "id": 0,
            "bytes": 1
          },
          "details": "Mass storage id to take picture",
          "lookup": {},
          "value": null
        },
        "lookup": {
          "0": "mass_storage_id"
        }
      },
      "Video": {
        "info": {
          "tagType": "cmd",
          "name": "Video",
          "id": 1
        },
        "details": "@deprecated Video record",
        "record": {
          "info": {
            "tagType": "arg",
            "name": "record",
            "type": "enum",
            "id": 0,
            "bytes": 4
          },
          "details": "Command to record video",
          "stop": {
            "info": {
              "tagType": "enum",
              "name": "stop",
              "id": 0
            },
            "details": "Stop the video recording",
            "lookup": {}
          },
          "start": {
            "info": {
              "tagType": "enum",
              "name": "start",
              "id": 1
            },
            "details": "Start the video recording",
            "lookup": {}
          },
          "lookup": {
            "0": "stop",
            "1": "start"
          },
          "value": null
        },
        "mass_storage_id": {
          "info": {
            "tagType": "arg",
            "name": "mass_storage_id",
            "type": "u8",
            "id": 1,
            "bytes": 1
          },
          "details": "Mass storage id to record",
          "lookup": {},
          "value": null
        },
        "lookup": {
          "0": "record",
          "1": "mass_storage_id"
        }
      },
      "PictureV2": {
        "info": {
          "tagType": "cmd",
          "name": "PictureV2",
          "id": 2
        },
        "details": "Take picture",
        "lookup": {}
      },
      "VideoV2": {
        "info": {
          "tagType": "cmd",
          "name": "VideoV2",
          "id": 3
        },
        "details": "Video record",
        "record": {
          "info": {
            "tagType": "arg",
            "name": "record",
            "type": "enum",
            "id": 0,
            "bytes": 4
          },
          "details": "Command to record video",
          "stop": {
            "info": {
              "tagType": "enum",
              "name": "stop",
              "id": 0
            },
            "details": "Stop the video recording",
            "lookup": {}
          },
          "start": {
            "info": {
              "tagType": "enum",
              "name": "start",
              "id": 1
            },
            "details": "Start the video recording",
            "lookup": {}
          },
          "lookup": {
            "0": "stop",
            "1": "start"
          },
          "value": null
        },
        "lookup": {
          "0": "record"
        }
      },
      "lookup": {
        "0": "Picture",
        "1": "Video",
        "2": "PictureV2",
        "3": "VideoV2"
      }
    },
    "MediaRecordState": {
      "info": {
        "tagType": "class",
        "name": "MediaRecordState",
        "id": 7
      },
      "details": "State of media recording",
      "PictureStateChanged": {
        "info": {
          "tagType": "cmd",
          "name": "PictureStateChanged",
          "id": 0
        },
        "details": "@deprecated State of picture recording",
        "state": {
          "info": {
            "tagType": "arg",
            "name": "state",
            "type": "u8",
            "id": 0,
            "bytes": 1
          },
          "details": "1 if picture has been taken, 0 otherwise",
          "lookup": {},
          "value": null
        },
        "mass_storage_id": {
          "info": {
            "tagType": "arg",
            "name": "mass_storage_id",
            "type": "u8",
            "id": 1,
            "bytes": 1
          },
          "details": "Mass storage id where the picture was recorded",
          "lookup": {},
          "value": null
        },
        "lookup": {
          "0": "state",
          "1": "mass_storage_id"
        }
      },
      "VideoStateChanged": {
        "info": {
          "tagType": "cmd",
          "name": "VideoStateChanged",
          "id": 1
        },
        "details": "@deprecated State of video recording",
        "state": {
          "info": {
            "tagType": "arg",
            "name": "state",
            "type": "enum",
            "id": 0,
            "bytes": 4
          },
          "details": "State of video",
          "stopped": {
            "info": {
              "tagType": "enum",
              "name": "stopped",
              "id": 0
            },
            "details": "Video was stopped",
            "lookup": {}
          },
          "started": {
            "info": {
              "tagType": "enum",
              "name": "started",
              "id": 1
            },
            "details": "Video was started",
            "lookup": {}
          },
          "failed": {
            "info": {
              "tagType": "enum",
              "name": "failed",
              "id": 2
            },
            "details": "Video was failed",
            "lookup": {}
          },
          "lookup": {
            "0": "stopped",
            "1": "started",
            "2": "failed"
          },
          "value": null
        },
        "mass_storage_id": {
          "info": {
            "tagType": "arg",
            "name": "mass_storage_id",
            "type": "u8",
            "id": 1,
            "bytes": 1
          },
          "details": "Mass storage id where the video was recorded",
          "lookup": {},
          "value": null
        },
        "lookup": {
          "0": "state",
          "1": "mass_storage_id"
        }
      },
      "PictureStateChangedV2": {
        "info": {
          "tagType": "cmd",
          "name": "PictureStateChangedV2",
          "id": 2
        },
        "details": "State of device picture recording changed",
        "state": {
          "info": {
            "tagType": "arg",
            "name": "state",
            "type": "enum",
            "id": 0,
            "bytes": 4
          },
          "details": "State of device picture recording",
          "ready": {
            "info": {
              "tagType": "enum",
              "name": "ready",
              "id": 0
            },
            "details": "The picture recording is ready",
            "lookup": {}
          },
          "busy": {
            "info": {
              "tagType": "enum",
              "name": "busy",
              "id": 1
            },
            "details": "The picture recording is busy",
            "lookup": {}
          },
          "notAvailable": {
            "info": {
              "tagType": "enum",
              "name": "notAvailable",
              "id": 2
            },
            "details": "The picture recording is not available",
            "lookup": {}
          },
          "lookup": {
            "0": "ready",
            "1": "busy",
            "2": "notAvailable"
          },
          "value": null
        },
        "error": {
          "info": {
            "tagType": "arg",
            "name": "error",
            "type": "enum",
            "id": 1,
            "bytes": 4
          },
          "details": "Error to explain the state",
          "ok": {
            "info": {
              "tagType": "enum",
              "name": "ok",
              "id": 0
            },
            "details": "No Error",
            "lookup": {}
          },
          "unknown": {
            "info": {
              "tagType": "enum",
              "name": "unknown",
              "id": 1
            },
            "details": "Unknown generic error",
            "lookup": {}
          },
          "camera_ko": {
            "info": {
              "tagType": "enum",
              "name": "camera_ko",
              "id": 2
            },
            "details": "Picture camera is out of order",
            "lookup": {}
          },
          "memoryFull": {
            "info": {
              "tagType": "enum",
              "name": "memoryFull",
              "id": 3
            },
            "details": "Memory full ; cannot save one additional picture",
            "lookup": {}
          },
          "lowBattery": {
            "info": {
              "tagType": "enum",
              "name": "lowBattery",
              "id": 4
            },
            "details": "Battery is too low to start/keep recording.",
            "lookup": {}
          },
          "lookup": {
            "0": "ok",
            "1": "unknown",
            "2": "camera_ko",
            "3": "memoryFull",
            "4": "lowBattery"
          },
          "value": null
        },
        "lookup": {
          "0": "state",
          "1": "error"
        }
      },
      "VideoStateChangedV2": {
        "info": {
          "tagType": "cmd",
          "name": "VideoStateChangedV2",
          "id": 3
        },
        "details": "State of device video recording changed",
        "state": {
          "info": {
            "tagType": "arg",
            "name": "state",
            "type": "enum",
            "id": 0,
            "bytes": 4
          },
          "details": "State of device video recording",
          "stopped": {
            "info": {
              "tagType": "enum",
              "name": "stopped",
              "id": 0
            },
            "details": "Video is stopped",
            "lookup": {}
          },
          "started": {
            "info": {
              "tagType": "enum",
              "name": "started",
              "id": 1
            },
            "details": "Video is started",
            "lookup": {}
          },
          "notAvailable": {
            "info": {
              "tagType": "enum",
              "name": "notAvailable",
              "id": 2
            },
            "details": "The video recording is not available",
            "lookup": {}
          },
          "lookup": {
            "0": "stopped",
            "1": "started",
            "2": "notAvailable"
          },
          "value": null
        },
        "error": {
          "info": {
            "tagType": "arg",
            "name": "error",
            "type": "enum",
            "id": 1,
            "bytes": 4
          },
          "details": "Error to explain the state",
          "ok": {
            "info": {
              "tagType": "enum",
              "name": "ok",
              "id": 0
            },
            "details": "No Error",
            "lookup": {}
          },
          "unknown": {
            "info": {
              "tagType": "enum",
              "name": "unknown",
              "id": 1
            },
            "details": "Unknown generic error",
            "lookup": {}
          },
          "camera_ko": {
            "info": {
              "tagType": "enum",
              "name": "camera_ko",
              "id": 2
            },
            "details": "Video camera is out of order",
            "lookup": {}
          },
          "memoryFull": {
            "info": {
              "tagType": "enum",
              "name": "memoryFull",
              "id": 3
            },
            "details": "Memory full ; cannot save one additional video",
            "lookup": {}
          },
          "lowBattery": {
            "info": {
              "tagType": "enum",
              "name": "lowBattery",
              "id": 4
            },
            "details": "Battery is too low to start/keep recording.",
            "lookup": {}
          },
          "lookup": {
            "0": "ok",
            "1": "unknown",
            "2": "camera_ko",
            "3": "memoryFull",
            "4": "lowBattery"
          },
          "value": null
        },
        "lookup": {
          "0": "state",
          "1": "error"
        }
      },
      "lookup": {
        "0": "PictureStateChanged",
        "1": "VideoStateChanged",
        "2": "PictureStateChangedV2",
        "3": "VideoStateChangedV2"
      }
    },
    "MediaRecordEvent": {
      "info": {
        "tagType": "class",
        "name": "MediaRecordEvent",
        "id": 20
      },
      "details": "Events of media recording",
      "PictureEventChanged": {
        "info": {
          "tagType": "cmd",
          "name": "PictureEventChanged",
          "id": 0,
          "content": "NOTIFICATION"
        },
        "details": "Event of picture recording",
        "event": {
          "info": {
            "tagType": "arg",
            "name": "event",
            "type": "enum",
            "id": 0,
            "bytes": 4
          },
          "details": "Last event of picture recording",
          "taken": {
            "info": {
              "tagType": "enum",
              "name": "taken",
              "id": 0
            },
            "details": "Picture taken and saved",
            "lookup": {}
          },
          "failed": {
            "info": {
              "tagType": "enum",
              "name": "failed",
              "id": 1
            },
            "details": "Picture failed",
            "lookup": {}
          },
          "lookup": {
            "0": "taken",
            "1": "failed"
          },
          "value": null
        },
        "error": {
          "info": {
            "tagType": "arg",
            "name": "error",
            "type": "enum",
            "id": 1,
            "bytes": 4
          },
          "details": "Error to explain the event",
          "ok": {
            "info": {
              "tagType": "enum",
              "name": "ok",
              "id": 0
            },
            "details": "No Error",
            "lookup": {}
          },
          "unknown": {
            "info": {
              "tagType": "enum",
              "name": "unknown",
              "id": 1
            },
            "details": "Unknown generic error ; only when state is failed",
            "lookup": {}
          },
          "busy": {
            "info": {
              "tagType": "enum",
              "name": "busy",
              "id": 2
            },
            "details": "Picture recording is busy ; only when state is failed",
            "lookup": {}
          },
          "notAvailable": {
            "info": {
              "tagType": "enum",
              "name": "notAvailable",
              "id": 3
            },
            "details": "Picture recording not available ; only when state is failed",
            "lookup": {}
          },
          "memoryFull": {
            "info": {
              "tagType": "enum",
              "name": "memoryFull",
              "id": 4
            },
            "details": "Memory full ; only when state is failed",
            "lookup": {}
          },
          "lowBattery": {
            "info": {
              "tagType": "enum",
              "name": "lowBattery",
              "id": 5
            },
            "details": "Battery is too low to record.",
            "lookup": {}
          },
          "lookup": {
            "0": "ok",
            "1": "unknown",
            "2": "busy",
            "3": "notAvailable",
            "4": "memoryFull",
            "5": "lowBattery"
          },
          "value": null
        },
        "lookup": {
          "0": "event",
          "1": "error"
        }
      },
      "VideoEventChanged": {
        "info": {
          "tagType": "cmd",
          "name": "VideoEventChanged",
          "id": 1,
          "content": "NOTIFICATION"
        },
        "details": "Event of video recording",
        "event": {
          "info": {
            "tagType": "arg",
            "name": "event",
            "type": "enum",
            "id": 0,
            "bytes": 4
          },
          "details": "Event of video recording",
          "start": {
            "info": {
              "tagType": "enum",
              "name": "start",
              "id": 0
            },
            "details": "Video start",
            "lookup": {}
          },
          "stop": {
            "info": {
              "tagType": "enum",
              "name": "stop",
              "id": 1
            },
            "details": "Video stop and saved",
            "lookup": {}
          },
          "failed": {
            "info": {
              "tagType": "enum",
              "name": "failed",
              "id": 2
            },
            "details": "Video failed",
            "lookup": {}
          },
          "lookup": {
            "0": "start",
            "1": "stop",
            "2": "failed"
          },
          "value": null
        },
        "error": {
          "info": {
            "tagType": "arg",
            "name": "error",
            "type": "enum",
            "id": 1,
            "bytes": 4
          },
          "details": "Error to explain the event",
          "ok": {
            "info": {
              "tagType": "enum",
              "name": "ok",
              "id": 0
            },
            "details": "No Error",
            "lookup": {}
          },
          "unknown": {
            "info": {
              "tagType": "enum",
              "name": "unknown",
              "id": 1
            },
            "details": "Unknown generic error ; only when state is failed",
            "lookup": {}
          },
          "busy": {
            "info": {
              "tagType": "enum",
              "name": "busy",
              "id": 2
            },
            "details": "Video recording is busy ; only when state is failed",
            "lookup": {}
          },
          "notAvailable": {
            "info": {
              "tagType": "enum",
              "name": "notAvailable",
              "id": 3
            },
            "details": "Video recording not available ; only when state is failed",
            "lookup": {}
          },
          "memoryFull": {
            "info": {
              "tagType": "enum",
              "name": "memoryFull",
              "id": 4
            },
            "details": "Memory full",
            "lookup": {}
          },
          "lowBattery": {
            "info": {
              "tagType": "enum",
              "name": "lowBattery",
              "id": 5
            },
            "details": "Battery is too low to record.",
            "lookup": {}
          },
          "autoStopped": {
            "info": {
              "tagType": "enum",
              "name": "autoStopped",
              "id": 6
            },
            "details": "Video was auto stopped",
            "lookup": {}
          },
          "lookup": {
            "0": "ok",
            "1": "unknown",
            "2": "busy",
            "3": "notAvailable",
            "4": "memoryFull",
            "5": "lowBattery",
            "6": "autoStopped"
          },
          "value": null
        },
        "lookup": {
          "0": "event",
          "1": "error"
        }
      },
      "lookup": {
        "0": "PictureEventChanged",
        "1": "VideoEventChanged"
      }
    },
    "NetworkSettings": {
      "info": {
        "tagType": "class",
        "name": "NetworkSettings",
        "id": 8
      },
      "details": "Network settings commands",
      "WifiSelection": {
        "info": {
          "tagType": "cmd",
          "name": "WifiSelection",
          "id": 0
        },
        "details": "Auto_select channel of choosen band",
        "type": {
          "info": {
            "tagType": "arg",
            "name": "type",
            "type": "enum",
            "id": 0,
            "bytes": 4
          },
          "details": "The type of wifi selection (auto, manual)",
          "auto": {
            "info": {
              "tagType": "enum",
              "name": "auto",
              "id": 0
            },
            "details": "Auto selection",
            "lookup": {}
          },
          "manual": {
            "info": {
              "tagType": "enum",
              "name": "manual",
              "id": 1
            },
            "details": "Manual selection",
            "lookup": {}
          },
          "lookup": {
            "0": "auto",
            "1": "manual"
          },
          "value": null
        },
        "band": {
          "info": {
            "tagType": "arg",
            "name": "band",
            "type": "enum",
            "id": 1,
            "bytes": 4
          },
          "details": "The allowed band(s) : 2.4 Ghz, 5 Ghz, or all",
          "_2_4ghz": {
            "info": {
              "tagType": "enum",
              "name": "_2_4ghz",
              "id": 0
            },
            "details": "2.4 GHz band",
            "lookup": {}
          },
          "_5ghz": {
            "info": {
              "tagType": "enum",
              "name": "_5ghz",
              "id": 1
            },
            "details": "5 GHz band",
            "lookup": {}
          },
          "all": {
            "info": {
              "tagType": "enum",
              "name": "all",
              "id": 2
            },
            "details": "Both 2.4 and 5 GHz bands",
            "lookup": {}
          },
          "lookup": {
            "0": "_2_4ghz",
            "1": "_5ghz",
            "2": "all"
          },
          "value": null
        },
        "channel": {
          "info": {
            "tagType": "arg",
            "name": "channel",
            "type": "u8",
            "id": 2,
            "bytes": 1
          },
          "details": "The channel (not used in auto mode)",
          "lookup": {},
          "value": null
        },
        "lookup": {
          "0": "type",
          "1": "band",
          "2": "channel"
        }
      },
      "lookup": {
        "0": "WifiSelection"
      }
    },
    "NetworkSettingsState": {
      "info": {
        "tagType": "class",
        "name": "NetworkSettingsState",
        "id": 9
      },
      "details": "Network settings state from product",
      "WifiSelectionChanged": {
        "info": {
          "tagType": "cmd",
          "name": "WifiSelectionChanged",
          "id": 0
        },
        "details": "Wifi selection from product",
        "type": {
          "info": {
            "tagType": "arg",
            "name": "type",
            "type": "enum",
            "id": 0,
            "bytes": 4
          },
          "details": "The type of wifi selection settings",
          "auto_all": {
            "info": {
              "tagType": "enum",
              "name": "auto_all",
              "id": 0
            },
            "details": "Auto selection",
            "lookup": {}
          },
          "auto__2_4ghz": {
            "info": {
              "tagType": "enum",
              "name": "auto__2_4ghz",
              "id": 1
            },
            "details": "Auto selection 2.4ghz",
            "lookup": {}
          },
          "auto__5ghz": {
            "info": {
              "tagType": "enum",
              "name": "auto__5ghz",
              "id": 2
            },
            "details": "Auto selection 5 ghz",
            "lookup": {}
          },
          "manual": {
            "info": {
              "tagType": "enum",
              "name": "manual",
              "id": 3
            },
            "details": "Manual selection",
            "lookup": {}
          },
          "lookup": {
            "0": "auto_all",
            "1": "auto__2_4ghz",
            "2": "auto__5ghz",
            "3": "manual"
          },
          "value": null
        },
        "band": {
          "info": {
            "tagType": "arg",
            "name": "band",
            "type": "enum",
            "id": 1,
            "bytes": 4
          },
          "details": "The actual wifi band state",
          "_2_4ghz": {
            "info": {
              "tagType": "enum",
              "name": "_2_4ghz",
              "id": 0
            },
            "details": "2.4 GHz band",
            "lookup": {}
          },
          "_5ghz": {
            "info": {
              "tagType": "enum",
              "name": "_5ghz",
              "id": 1
            },
            "details": "5 GHz band",
            "lookup": {}
          },
          "all": {
            "info": {
              "tagType": "enum",
              "name": "all",
              "id": 2
            },
            "details": "Both 2.4 and 5 GHz bands",
            "lookup": {}
          },
          "lookup": {
            "0": "_2_4ghz",
            "1": "_5ghz",
            "2": "all"
          },
          "value": null
        },
        "channel": {
          "info": {
            "tagType": "arg",
            "name": "channel",
            "type": "u8",
            "id": 2,
            "bytes": 1
          },
          "details": "The channel (depends of the band)",
          "lookup": {},
          "value": null
        },
        "lookup": {
          "0": "type",
          "1": "band",
          "2": "channel"
        }
      },
      "lookup": {
        "0": "WifiSelectionChanged"
      }
    },
    "Network": {
      "info": {
        "tagType": "class",
        "name": "Network",
        "id": 10
      },
      "details": "Network related commands",
      "WifiScan": {
        "info": {
          "tagType": "cmd",
          "name": "WifiScan",
          "id": 0
        },
        "details": "Launches wifi network scan",
        "band": {
          "info": {
            "tagType": "arg",
            "name": "band",
            "type": "enum",
            "id": 0,
            "bytes": 4
          },
          "details": "The band(s) : 2.4 Ghz, 5 Ghz, or both",
          "_2_4ghz": {
            "info": {
              "tagType": "enum",
              "name": "_2_4ghz",
              "id": 0
            },
            "details": "2.4 GHz band",
            "lookup": {}
          },
          "_5ghz": {
            "info": {
              "tagType": "enum",
              "name": "_5ghz",
              "id": 1
            },
            "details": "5 GHz band",
            "lookup": {}
          },
          "all": {
            "info": {
              "tagType": "enum",
              "name": "all",
              "id": 2
            },
            "details": "Both 2.4 and 5 GHz bands",
            "lookup": {}
          },
          "lookup": {
            "0": "_2_4ghz",
            "1": "_5ghz",
            "2": "all"
          },
          "value": null
        },
        "lookup": {
          "0": "band"
        }
      },
      "WifiAuthChannel": {
        "info": {
          "tagType": "cmd",
          "name": "WifiAuthChannel",
          "id": 1
        },
        "details": "Controller inquire the list of authorized wifi channels.",
        "lookup": {}
      },
      "lookup": {
        "0": "WifiScan",
        "1": "WifiAuthChannel"
      }
    },
    "NetworkState": {
      "info": {
        "tagType": "class",
        "name": "NetworkState",
        "id": 11
      },
      "details": "Network state from Product",
      "WifiScanListChanged": {
        "info": {
          "tagType": "cmd",
          "name": "WifiScanListChanged",
          "id": 0,
          "type": "MAP_ITEM"
        },
        "details": "One scanning result found",
        "ssid": {
          "info": {
            "tagType": "arg",
            "name": "ssid",
            "type": "string",
            "id": 0,
            "bytes": 1
          },
          "details": "SSID of the AP",
          "lookup": {},
          "value": null
        },
        "rssi": {
          "info": {
            "tagType": "arg",
            "name": "rssi",
            "type": "i16",
            "id": 1,
            "bytes": 2
          },
          "details": "RSSI of the AP in dbm (negative value)",
          "lookup": {},
          "value": null
        },
        "band": {
          "info": {
            "tagType": "arg",
            "name": "band",
            "type": "enum",
            "id": 2,
            "bytes": 4
          },
          "details": "The band : 2.4 GHz or 5 GHz",
          "_2_4ghz": {
            "info": {
              "tagType": "enum",
              "name": "_2_4ghz",
              "id": 0
            },
            "details": "2.4 GHz band",
            "lookup": {}
          },
          "_5ghz": {
            "info": {
              "tagType": "enum",
              "name": "_5ghz",
              "id": 1
            },
            "details": "5 GHz band",
            "lookup": {}
          },
          "lookup": {
            "0": "_2_4ghz",
            "1": "_5ghz"
          },
          "value": null
        },
        "channel": {
          "info": {
            "tagType": "arg",
            "name": "channel",
            "type": "u8",
            "id": 3,
            "bytes": 1
          },
          "details": "Channel of the AP",
          "lookup": {},
          "value": null
        },
        "lookup": {
          "0": "ssid",
          "1": "rssi",
          "2": "band",
          "3": "channel"
        }
      },
      "AllWifiScanChanged": {
        "info": {
          "tagType": "cmd",
          "name": "AllWifiScanChanged",
          "id": 1
        },
        "details": "State sent when all scanning result sent",
        "lookup": {}
      },
      "WifiAuthChannelListChanged": {
        "info": {
          "tagType": "cmd",
          "name": "WifiAuthChannelListChanged",
          "id": 2,
          "type": "LIST_ITEM"
        },
        "details": "Notify of an Authorized Channel.",
        "band": {
          "info": {
            "tagType": "arg",
            "name": "band",
            "type": "enum",
            "id": 0,
            "bytes": 4
          },
          "details": "The band of this channel : 2.4 GHz or 5 GHz",
          "_2_4ghz": {
            "info": {
              "tagType": "enum",
              "name": "_2_4ghz",
              "id": 0
            },
            "details": "2.4 GHz band",
            "lookup": {}
          },
          "_5ghz": {
            "info": {
              "tagType": "enum",
              "name": "_5ghz",
              "id": 1
            },
            "details": "5 GHz band",
            "lookup": {}
          },
          "lookup": {
            "0": "_2_4ghz",
            "1": "_5ghz"
          },
          "value": null
        },
        "channel": {
          "info": {
            "tagType": "arg",
            "name": "channel",
            "type": "u8",
            "id": 1,
            "bytes": 1
          },
          "details": "The authorized channel.",
          "lookup": {},
          "value": null
        },
        "in_or_out": {
          "info": {
            "tagType": "arg",
            "name": "in_or_out",
            "type": "u8",
            "id": 2,
            "bytes": 1
          },
          "details": "Bit 0 is 1 if channel is authorized outside (0 otherwise) ; Bit 1 is 1 if channel is authorized inside (0 otherwise)",
          "lookup": {},
          "value": null
        },
        "lookup": {
          "0": "band",
          "1": "channel",
          "2": "in_or_out"
        }
      },
      "AllWifiAuthChannelChanged": {
        "info": {
          "tagType": "cmd",
          "name": "AllWifiAuthChannelChanged",
          "id": 3
        },
        "details": "Notify the end of the list of Authorized wifi Channel.",
        "lookup": {}
      },
      "LinkQualityChanged": {
        "info": {
          "tagType": "cmd",
          "name": "LinkQualityChanged",
          "id": 4
        },
        "details": "Notification sent by the firmware to give an indication of the WiFi link quality.",
        "quality": {
          "info": {
            "tagType": "arg",
            "name": "quality",
            "type": "u8",
            "id": 0,
            "bytes": 1
          },
          "details": "The WiFi link quality in range 0_6, the higher the value, the higher the link quality.",
          "lookup": {},
          "value": null
        },
        "lookup": {
          "0": "quality"
        }
      },
      "lookup": {
        "0": "WifiScanListChanged",
        "1": "AllWifiScanChanged",
        "2": "WifiAuthChannelListChanged",
        "3": "AllWifiAuthChannelChanged",
        "4": "LinkQualityChanged"
      }
    },
    "AudioSettings": {
      "info": {
        "tagType": "class",
        "name": "AudioSettings",
        "id": 12
      },
      "details": "Audio settings.",
      "MasterVolume": {
        "info": {
          "tagType": "cmd",
          "name": "MasterVolume",
          "id": 0
        },
        "details": "Master volume control.",
        "volume": {
          "info": {
            "tagType": "arg",
            "name": "volume",
            "type": "u8",
            "id": 0,
            "bytes": 1
          },
          "details": "Master audio volume [0_100].",
          "lookup": {},
          "value": null
        },
        "lookup": {
          "0": "volume"
        }
      },
      "Theme": {
        "info": {
          "tagType": "cmd",
          "name": "Theme",
          "id": 1
        },
        "details": "Audio Theme.",
        "theme": {
          "info": {
            "tagType": "arg",
            "name": "theme",
            "type": "enum",
            "id": 0,
            "bytes": 4
          },
          "details": "The audio theme to set.",
          "default": {
            "info": {
              "tagType": "enum",
              "name": "default",
              "id": 0
            },
            "details": "Default audio theme (depends on the product color)",
            "lookup": {}
          },
          "robot": {
            "info": {
              "tagType": "enum",
              "name": "robot",
              "id": 1
            },
            "details": "Robot audio theme.",
            "lookup": {}
          },
          "insect": {
            "info": {
              "tagType": "enum",
              "name": "insect",
              "id": 2
            },
            "details": "Insect audio theme.",
            "lookup": {}
          },
          "monster": {
            "info": {
              "tagType": "enum",
              "name": "monster",
              "id": 3
            },
            "details": "Monster audio theme.",
            "lookup": {}
          },
          "lookup": {
            "0": "default",
            "1": "robot",
            "2": "insect",
            "3": "monster"
          },
          "value": null
        },
        "lookup": {
          "0": "theme"
        }
      },
      "lookup": {
        "0": "MasterVolume",
        "1": "Theme"
      }
    },
    "AudioSettingsState": {
      "info": {
        "tagType": "class",
        "name": "AudioSettingsState",
        "id": 13
      },
      "details": "Audio settings state.",
      "MasterVolumeChanged": {
        "info": {
          "tagType": "cmd",
          "name": "MasterVolumeChanged",
          "id": 0
        },
        "details": "Master volume control.",
        "volume": {
          "info": {
            "tagType": "arg",
            "name": "volume",
            "type": "u8",
            "id": 0,
            "bytes": 1
          },
          "details": "Master audio volume [0_100].",
          "lookup": {},
          "value": null
        },
        "lookup": {
          "0": "volume"
        }
      },
      "ThemeChanged": {
        "info": {
          "tagType": "cmd",
          "name": "ThemeChanged",
          "id": 1
        },
        "details": "Command to notify controller of new Audio Theme.",
        "theme": {
          "info": {
            "tagType": "arg",
            "name": "theme",
            "type": "enum",
            "id": 0,
            "bytes": 4
          },
          "details": "The audio theme to set.",
          "default": {
            "info": {
              "tagType": "enum",
              "name": "default",
              "id": 0
            },
            "details": "Default audio theme (depends on the product color)",
            "lookup": {}
          },
          "robot": {
            "info": {
              "tagType": "enum",
              "name": "robot",
              "id": 1
            },
            "details": "Robot audio theme.",
            "lookup": {}
          },
          "insect": {
            "info": {
              "tagType": "enum",
              "name": "insect",
              "id": 2
            },
            "details": "Insect audio theme.",
            "lookup": {}
          },
          "monster": {
            "info": {
              "tagType": "enum",
              "name": "monster",
              "id": 3
            },
            "details": "Monster audio theme.",
            "lookup": {}
          },
          "lookup": {
            "0": "default",
            "1": "robot",
            "2": "insect",
            "3": "monster"
          },
          "value": null
        },
        "lookup": {
          "0": "theme"
        }
      },
      "lookup": {
        "0": "MasterVolumeChanged",
        "1": "ThemeChanged"
      }
    },
    "RoadPlan": {
      "info": {
        "tagType": "class",
        "name": "RoadPlan",
        "id": 14
      },
      "details": "RoadPlan commands.",
      "AllScriptsMetadata": {
        "info": {
          "tagType": "cmd",
          "name": "AllScriptsMetadata",
          "id": 0
        },
        "details": "Command to ask device all metadata scripts.",
        "lookup": {}
      },
      "ScriptUploaded": {
        "info": {
          "tagType": "cmd",
          "name": "ScriptUploaded",
          "id": 1
        },
        "details": "Notify device that a new file has been uploaded.",
        "uuid": {
          "info": {
            "tagType": "arg",
            "name": "uuid",
            "type": "string",
            "id": 0,
            "bytes": 1
          },
          "details": "UUID of uploaded file.",
          "lookup": {},
          "value": null
        },
        "md5Hash": {
          "info": {
            "tagType": "arg",
            "name": "md5Hash",
            "type": "string",
            "id": 1,
            "bytes": 1
          },
          "details": "MD5 hash code computed over file.",
          "lookup": {},
          "value": null
        },
        "lookup": {
          "0": "uuid",
          "1": "md5Hash"
        }
      },
      "ScriptDelete": {
        "info": {
          "tagType": "cmd",
          "name": "ScriptDelete",
          "id": 2
        },
        "details": "Ask the device to delete a script.",
        "uuid": {
          "info": {
            "tagType": "arg",
            "name": "uuid",
            "type": "string",
            "id": 0,
            "bytes": 1
          },
          "details": "UUID of the file to delete.",
          "lookup": {},
          "value": null
        },
        "lookup": {
          "0": "uuid"
        }
      },
      "PlayScript": {
        "info": {
          "tagType": "cmd",
          "name": "PlayScript",
          "id": 3
        },
        "details": "Ask the device to play a script.",
        "uuid": {
          "info": {
            "tagType": "arg",
            "name": "uuid",
            "type": "string",
            "id": 0,
            "bytes": 1
          },
          "details": "UUID of the file to play.",
          "lookup": {},
          "value": null
        },
        "lookup": {
          "0": "uuid"
        }
      },
      "lookup": {
        "0": "AllScriptsMetadata",
        "1": "ScriptUploaded",
        "2": "ScriptDelete",
        "3": "PlayScript"
      }
    },
    "RoadPlanState": {
      "info": {
        "tagType": "class",
        "name": "RoadPlanState",
        "id": 15
      },
      "details": "RoadPlan command responses.",
      "ScriptMetadataListChanged": {
        "info": {
          "tagType": "cmd",
          "name": "ScriptMetadataListChanged",
          "id": 0,
          "type": "MAP_ITEM"
        },
        "details": "Update the controller with metadata.",
        "uuid": {
          "info": {
            "tagType": "arg",
            "name": "uuid",
            "type": "string",
            "id": 0,
            "bytes": 1
          },
          "details": "Script uuid for which metadata changed.",
          "lookup": {},
          "value": null
        },
        "version": {
          "info": {
            "tagType": "arg",
            "name": "version",
            "type": "u8",
            "id": 1,
            "bytes": 1
          },
          "details": "Version number for this script.",
          "lookup": {},
          "value": null
        },
        "product": {
          "info": {
            "tagType": "arg",
            "name": "product",
            "type": "string",
            "id": 2,
            "bytes": 1
          },
          "details": "Product targeted by script.",
          "lookup": {},
          "value": null
        },
        "name": {
          "info": {
            "tagType": "arg",
            "name": "name",
            "type": "string",
            "id": 3,
            "bytes": 1
          },
          "details": "Display name of the script.",
          "lookup": {},
          "value": null
        },
        "lastModified": {
          "info": {
            "tagType": "arg",
            "name": "lastModified",
            "type": "u64",
            "id": 4,
            "bytes": 1
          },
          "details": "Timestamp relative to the UNIX epoch of the last time the file was modified.",
          "lookup": {},
          "value": null
        },
        "lookup": {
          "0": "uuid",
          "1": "version",
          "2": "product",
          "3": "name",
          "4": "lastModified"
        }
      },
      "AllScriptsMetadataChanged": {
        "info": {
          "tagType": "cmd",
          "name": "AllScriptsMetadataChanged",
          "id": 1
        },
        "details": "Notify controller that all script metadatas are updated.",
        "lookup": {}
      },
      "ScriptUploadChanged": {
        "info": {
          "tagType": "cmd",
          "name": "ScriptUploadChanged",
          "id": 2
        },
        "details": "Device response to ScriptUploaded command.",
        "resultCode": {
          "info": {
            "tagType": "arg",
            "name": "resultCode",
            "type": "enum",
            "id": 0,
            "bytes": 4
          },
          "details": "Error code.",
          "error_ok": {
            "info": {
              "tagType": "enum",
              "name": "error_ok",
              "id": 0
            },
            "details": "The script was parsed successfully.",
            "lookup": {}
          },
          "error_file_corrupted": {
            "info": {
              "tagType": "enum",
              "name": "error_file_corrupted",
              "id": 1
            },
            "details": "The MD5 hash codes are different or file is unreadable.",
            "lookup": {}
          },
          "error_invalid_format": {
            "info": {
              "tagType": "enum",
              "name": "error_invalid_format",
              "id": 2
            },
            "details": "The parser is not well formed or can not be parsed.",
            "lookup": {}
          },
          "error_file_too_large": {
            "info": {
              "tagType": "enum",
              "name": "error_file_too_large",
              "id": 3
            },
            "details": "The file is larger than maximum allowed size.",
            "lookup": {}
          },
          "error_unsupported": {
            "info": {
              "tagType": "enum",
              "name": "error_unsupported",
              "id": 4
            },
            "details": "Script version is not supported by device.",
            "lookup": {}
          },
          "lookup": {
            "0": "error_ok",
            "1": "error_file_corrupted",
            "2": "error_invalid_format",
            "3": "error_file_too_large",
            "4": "error_unsupported"
          },
          "value": null
        },
        "lookup": {
          "0": "resultCode"
        }
      },
      "ScriptDeleteChanged": {
        "info": {
          "tagType": "cmd",
          "name": "ScriptDeleteChanged",
          "id": 3
        },
        "details": "Device response to ScriptDelete command.",
        "resultCode": {
          "info": {
            "tagType": "arg",
            "name": "resultCode",
            "type": "enum",
            "id": 0,
            "bytes": 4
          },
          "details": "Error code.",
          "error_ok": {
            "info": {
              "tagType": "enum",
              "name": "error_ok",
              "id": 0
            },
            "details": "The script was deleted successfully.",
            "lookup": {}
          },
          "error_no_such_script": {
            "info": {
              "tagType": "enum",
              "name": "error_no_such_script",
              "id": 1
            },
            "details": "No script with this uuid exists.",
            "lookup": {}
          },
          "error_internal_failure": {
            "info": {
              "tagType": "enum",
              "name": "error_internal_failure",
              "id": 2
            },
            "details": "An internal error occured while attempting to delete the script.",
            "lookup": {}
          },
          "lookup": {
            "0": "error_ok",
            "1": "error_no_such_script",
            "2": "error_internal_failure"
          },
          "value": null
        },
        "lookup": {
          "0": "resultCode"
        }
      },
      "PlayScriptChanged": {
        "info": {
          "tagType": "cmd",
          "name": "PlayScriptChanged",
          "id": 4
        },
        "details": "Device response to PlayScript command.",
        "resultCode": {
          "info": {
            "tagType": "arg",
            "name": "resultCode",
            "type": "enum",
            "id": 0,
            "bytes": 4
          },
          "details": "Error code.",
          "script_started": {
            "info": {
              "tagType": "enum",
              "name": "script_started",
              "id": 0
            },
            "details": "The script started playing successfully.",
            "lookup": {}
          },
          "script_finished": {
            "info": {
              "tagType": "enum",
              "name": "script_finished",
              "id": 1
            },
            "details": "The script finished successfully.",
            "lookup": {}
          },
          "script_no_such_script": {
            "info": {
              "tagType": "enum",
              "name": "script_no_such_script",
              "id": 2
            },
            "details": "No script with this uuid exists.",
            "lookup": {}
          },
          "script_error": {
            "info": {
              "tagType": "enum",
              "name": "script_error",
              "id": 3
            },
            "details": "An error occured while playing the script.",
            "lookup": {}
          },
          "lookup": {
            "0": "script_started",
            "1": "script_finished",
            "2": "script_no_such_script",
            "3": "script_error"
          },
          "value": null
        },
        "lookup": {
          "0": "resultCode"
        }
      },
      "lookup": {
        "0": "ScriptMetadataListChanged",
        "1": "AllScriptsMetadataChanged",
        "2": "ScriptUploadChanged",
        "3": "ScriptDeleteChanged",
        "4": "PlayScriptChanged"
      }
    },
    "SpeedSettings": {
      "info": {
        "tagType": "class",
        "name": "SpeedSettings",
        "id": 16
      },
      "details": "Speed Settings commands",
      "Outdoor": {
        "info": {
          "tagType": "cmd",
          "name": "Outdoor",
          "id": 0
        },
        "details": "@deprecated Outdoor property",
        "outdoor": {
          "info": {
            "tagType": "arg",
            "name": "outdoor",
            "type": "u8",
            "id": 0,
            "bytes": 1
          },
          "details": "1 if outdoor, 0 if indoor",
          "lookup": {},
          "value": null
        },
        "lookup": {
          "0": "outdoor"
        }
      },
      "lookup": {
        "0": "Outdoor"
      }
    },
    "SpeedSettingsState": {
      "info": {
        "tagType": "class",
        "name": "SpeedSettingsState",
        "id": 17
      },
      "details": "Speed Settings state from product",
      "OutdoorChanged": {
        "info": {
          "tagType": "cmd",
          "name": "OutdoorChanged",
          "id": 0
        },
        "details": "@deprecated Outdoor property sent by product",
        "outdoor": {
          "info": {
            "tagType": "arg",
            "name": "outdoor",
            "type": "u8",
            "id": 0,
            "bytes": 1
          },
          "details": "1 if outdoor, 0 if indoor",
          "lookup": {},
          "value": null
        },
        "lookup": {
          "0": "outdoor"
        }
      },
      "lookup": {
        "0": "OutdoorChanged"
      }
    },
    "MediaStreaming": {
      "info": {
        "tagType": "class",
        "name": "MediaStreaming",
        "id": 18
      },
      "details": "Control media streaming behavior.",
      "VideoEnable": {
        "info": {
          "tagType": "cmd",
          "name": "VideoEnable",
          "id": 0
        },
        "details": "Enable/disable video streaming.",
        "enable": {
          "info": {
            "tagType": "arg",
            "name": "enable",
            "type": "u8",
            "id": 0,
            "bytes": 1
          },
          "details": "1 to enable, 0 to disable.",
          "lookup": {},
          "value": null
        },
        "lookup": {
          "0": "enable"
        }
      },
      "lookup": {
        "0": "VideoEnable"
      }
    },
    "MediaStreamingState": {
      "info": {
        "tagType": "class",
        "name": "MediaStreamingState",
        "id": 19
      },
      "details": "Media streaming status.",
      "VideoEnableChanged": {
        "info": {
          "tagType": "cmd",
          "name": "VideoEnableChanged",
          "id": 0
        },
        "details": "Return video streaming status.",
        "enabled": {
          "info": {
            "tagType": "arg",
            "name": "enabled",
            "type": "enum",
            "id": 0,
            "bytes": 4
          },
          "details": "Current video streaming status.",
          "enabled": {
            "info": {
              "tagType": "enum",
              "name": "enabled",
              "id": 0
            },
            "details": "Video streaming is enabled.",
            "lookup": {}
          },
          "disabled": {
            "info": {
              "tagType": "enum",
              "name": "disabled",
              "id": 1
            },
            "details": "Video streaming is disabled.",
            "lookup": {}
          },
          "error": {
            "info": {
              "tagType": "enum",
              "name": "error",
              "id": 2
            },
            "details": "Video streaming failed to start.",
            "lookup": {}
          },
          "lookup": {
            "0": "enabled",
            "1": "disabled",
            "2": "error"
          },
          "value": null
        },
        "lookup": {
          "0": "enabled"
        }
      },
      "lookup": {
        "0": "VideoEnableChanged"
      }
    },
    "VideoSettings": {
      "info": {
        "tagType": "class",
        "name": "VideoSettings",
        "id": 21
      },
      "details": "Video settings.",
      "Autorecord": {
        "info": {
          "tagType": "cmd",
          "name": "Autorecord",
          "id": 0
        },
        "details": "Set video automatic recording state.",
        "enabled": {
          "info": {
            "tagType": "arg",
            "name": "enabled",
            "type": "u8",
            "id": 0,
            "bytes": 1
          },
          "details": "0: Disabled 1: Enabled.",
          "lookup": {},
          "value": null
        },
        "lookup": {
          "0": "enabled"
        }
      },
      "lookup": {
        "0": "Autorecord"
      }
    },
    "VideoSettingsState": {
      "info": {
        "tagType": "class",
        "name": "VideoSettingsState",
        "id": 22
      },
      "details": "Video settings state.",
      "AutorecordChanged": {
        "info": {
          "tagType": "cmd",
          "name": "AutorecordChanged",
          "id": 0
        },
        "details": "Get video automatic recording status.",
        "enabled": {
          "info": {
            "tagType": "arg",
            "name": "enabled",
            "type": "u8",
            "id": 0,
            "bytes": 1
          },
          "details": "0: Disabled 1: Enabled.",
          "lookup": {},
          "value": null
        },
        "lookup": {
          "0": "enabled"
        }
      },
      "lookup": {
        "0": "AutorecordChanged"
      }
    },
    "lookup": {
      "0": "Piloting",
      "1": "PilotingState",
      "2": "Animations",
      "3": "AnimationsState",
      "5": "SettingsState",
      "6": "MediaRecord",
      "7": "MediaRecordState",
      "8": "NetworkSettings",
      "9": "NetworkSettingsState",
      "10": "Network",
      "11": "NetworkState",
      "12": "AudioSettings",
      "13": "AudioSettingsState",
      "14": "RoadPlan",
      "15": "RoadPlanState",
      "16": "SpeedSettings",
      "17": "SpeedSettingsState",
      "18": "MediaStreaming",
      "19": "MediaStreamingState",
      "20": "MediaRecordEvent",
      "21": "VideoSettings",
      "22": "VideoSettingsState"
    }
  },
  "lookup": {
    "3": "jpsumo"
  }
}

module.exports=projects;
              