'use strict';
/*************************************************\
generated from arsdk-xml/xml/*.xml
generated by utils/convertSDK.js
generated on : 2/20/2017, 8:59:08 PM
\**************************************************/
const projects={
  "minidrone": {
    "info": {
      "tagType": "project",
      "name": "minidrone",
      "id": 2
    },
    "details": "All MiniDrone_only commands",
    "Piloting": {
      "info": {
        "tagType": "class",
        "name": "Piloting",
        "id": 0
      },
      "details": "All commands related to piloting the MiniDrone",
      "FlatTrim": {
        "info": {
          "tagType": "cmd",
          "name": "FlatTrim",
          "id": 0
        },
        "details": "Do a flat trim",
        "lookup": {}
      },
      "TakeOff": {
        "info": {
          "tagType": "cmd",
          "name": "TakeOff",
          "id": 1
        },
        "details": "Ask the drone to take off",
        "lookup": {}
      },
      "PCMD": {
        "info": {
          "tagType": "cmd",
          "name": "PCMD",
          "id": 2,
          "buffer": "NON_ACK"
        },
        "details": "Ask the drone to move around.",
        "flag": {
          "info": {
            "tagType": "arg",
            "name": "flag",
            "type": "u8",
            "id": 0,
            "bytes": 1
          },
          "details": "Boolean flag to activate roll/pitch movement",
          "lookup": {},
          "value": null
        },
        "roll": {
          "info": {
            "tagType": "arg",
            "name": "roll",
            "type": "i8",
            "id": 1,
            "bytes": 1
          },
          "details": "Roll consign for the MiniDrone [_100;100]",
          "lookup": {},
          "value": null
        },
        "pitch": {
          "info": {
            "tagType": "arg",
            "name": "pitch",
            "type": "i8",
            "id": 2,
            "bytes": 1
          },
          "details": "Pitch consign for the MiniDrone [_100;100]",
          "lookup": {},
          "value": null
        },
        "yaw": {
          "info": {
            "tagType": "arg",
            "name": "yaw",
            "type": "i8",
            "id": 3,
            "bytes": 1
          },
          "details": "Yaw consign for the MiniDrone [_100;100]",
          "lookup": {},
          "value": null
        },
        "gaz": {
          "info": {
            "tagType": "arg",
            "name": "gaz",
            "type": "i8",
            "id": 4,
            "bytes": 1
          },
          "details": "Gaz consign for the MiniDrone [_100;100]",
          "lookup": {},
          "value": null
        },
        "timestamp": {
          "info": {
            "tagType": "arg",
            "name": "timestamp",
            "type": "u32",
            "id": 5,
            "bytes": 4
          },
          "details": "Timestamp in miliseconds. Not an absolute time. (Typically 0 = time of connexion).",
          "lookup": {},
          "value": null
        },
        "lookup": {
          "0": "flag",
          "1": "roll",
          "2": "pitch",
          "3": "yaw",
          "4": "gaz",
          "5": "timestamp"
        }
      },
      "Landing": {
        "info": {
          "tagType": "cmd",
          "name": "Landing",
          "id": 3
        },
        "details": "Ask the MiniDrone to land",
        "lookup": {}
      },
      "Emergency": {
        "info": {
          "tagType": "cmd",
          "name": "Emergency",
          "id": 4,
          "buffer": "HIGH_PRIO",
          "timeout": "RETRY"
        },
        "details": "Put drone in emergency state",
        "lookup": {}
      },
      "AutoTakeOffMode": {
        "info": {
          "tagType": "cmd",
          "name": "AutoTakeOffMode",
          "id": 5
        },
        "details": "Set MiniDrone automatic take off mode",
        "state": {
          "info": {
            "tagType": "arg",
            "name": "state",
            "type": "u8",
            "id": 0,
            "bytes": 1
          },
          "details": "State of automatic take off mode",
          "lookup": {},
          "value": null
        },
        "lookup": {
          "0": "state"
        }
      },
      "FlyingMode": {
        "info": {
          "tagType": "cmd",
          "name": "FlyingMode",
          "id": 6
        },
        "details": "Set drone FlyingMode. Only supported by WingX",
        "mode": {
          "info": {
            "tagType": "arg",
            "name": "mode",
            "type": "u8",
            "id": 0,
            "bytes": 1
          },
          "details": "Drone Flying Mode",
          "quadricopter": {
            "info": {
              "tagType": "enum",
              "name": "quadricopter",
              "id": 0
            },
            "details": "Fly as a quadrictopter",
            "lookup": {}
          },
          "plane_forward": {
            "info": {
              "tagType": "enum",
              "name": "plane_forward",
              "id": 1
            },
            "details": "Fly as a plane in forward mode",
            "lookup": {}
          },
          "plane_backward": {
            "info": {
              "tagType": "enum",
              "name": "plane_backward",
              "id": 2
            },
            "details": "Fly as a plane in backward mode",
            "lookup": {}
          },
          "lookup": {
            "0": "quadricopter",
            "1": "plane_forward",
            "2": "plane_backward"
          },
          "value": null
        },
        "lookup": {
          "0": "mode"
        }
      },
      "PlaneGearBox": {
        "info": {
          "tagType": "cmd",
          "name": "PlaneGearBox",
          "id": 7
        },
        "details": "Set Plane Gear Box. Only supported by WingX",
        "state": {
          "info": {
            "tagType": "arg",
            "name": "state",
            "type": "enum",
            "id": 0,
            "bytes": 4
          },
          "details": "Plane Gear Box",
          "gear_1": {
            "info": {
              "tagType": "enum",
              "name": "gear_1",
              "id": 0
            },
            "details": "Gear 1. Low speed",
            "lookup": {}
          },
          "gear_2": {
            "info": {
              "tagType": "enum",
              "name": "gear_2",
              "id": 1
            },
            "details": "Gear 2. Middle speed",
            "lookup": {}
          },
          "gear_3": {
            "info": {
              "tagType": "enum",
              "name": "gear_3",
              "id": 2
            },
            "details": "Gear 3. High speed",
            "lookup": {}
          },
          "lookup": {
            "0": "gear_1",
            "1": "gear_2",
            "2": "gear_3"
          },
          "value": null
        },
        "lookup": {
          "0": "state"
        }
      },
      "lookup": {
        "0": "FlatTrim",
        "1": "TakeOff",
        "2": "PCMD",
        "3": "Landing",
        "4": "Emergency",
        "5": "AutoTakeOffMode",
        "6": "FlyingMode",
        "7": "PlaneGearBox"
      }
    },
    "PilotingState": {
      "info": {
        "tagType": "class",
        "name": "PilotingState",
        "id": 3
      },
      "details": "Occasional information",
      "FlatTrimChanged": {
        "info": {
          "tagType": "cmd",
          "name": "FlatTrimChanged",
          "id": 0
        },
        "details": "MiniDrone send flat trim was correctly processed",
        "lookup": {}
      },
      "FlyingStateChanged": {
        "info": {
          "tagType": "cmd",
          "name": "FlyingStateChanged",
          "id": 1
        },
        "details": "Drone flying state changed",
        "state": {
          "info": {
            "tagType": "arg",
            "name": "state",
            "type": "enum",
            "id": 0,
            "bytes": 4
          },
          "details": "Drone flying state",
          "landed": {
            "info": {
              "tagType": "enum",
              "name": "landed",
              "id": 0
            },
            "details": "Landed state",
            "lookup": {}
          },
          "takingoff": {
            "info": {
              "tagType": "enum",
              "name": "takingoff",
              "id": 1
            },
            "details": "Taking off state",
            "lookup": {}
          },
          "hovering": {
            "info": {
              "tagType": "enum",
              "name": "hovering",
              "id": 2
            },
            "details": "Hovering state",
            "lookup": {}
          },
          "flying": {
            "info": {
              "tagType": "enum",
              "name": "flying",
              "id": 3
            },
            "details": "Flying state",
            "lookup": {}
          },
          "landing": {
            "info": {
              "tagType": "enum",
              "name": "landing",
              "id": 4
            },
            "details": "Landing state",
            "lookup": {}
          },
          "emergency": {
            "info": {
              "tagType": "enum",
              "name": "emergency",
              "id": 5
            },
            "details": "Emergency state",
            "lookup": {}
          },
          "rolling": {
            "info": {
              "tagType": "enum",
              "name": "rolling",
              "id": 6
            },
            "details": "Rolling state",
            "lookup": {}
          },
          "init": {
            "info": {
              "tagType": "enum",
              "name": "init",
              "id": 7
            },
            "details": "Initializing state (user should let the drone steady for a while)",
            "lookup": {}
          },
          "lookup": {
            "0": "landed",
            "1": "takingoff",
            "2": "hovering",
            "3": "flying",
            "4": "landing",
            "5": "emergency",
            "6": "rolling",
            "7": "init"
          },
          "value": null
        },
        "lookup": {
          "0": "state"
        }
      },
      "AlertStateChanged": {
        "info": {
          "tagType": "cmd",
          "name": "AlertStateChanged",
          "id": 2
        },
        "details": "Drone alert state changed",
        "state": {
          "info": {
            "tagType": "arg",
            "name": "state",
            "type": "enum",
            "id": 0,
            "bytes": 4
          },
          "details": "Drone alert state",
          "none": {
            "info": {
              "tagType": "enum",
              "name": "none",
              "id": 0
            },
            "details": "No alert",
            "lookup": {}
          },
          "user": {
            "info": {
              "tagType": "enum",
              "name": "user",
              "id": 1
            },
            "details": "User emergency alert",
            "lookup": {}
          },
          "cut_out": {
            "info": {
              "tagType": "enum",
              "name": "cut_out",
              "id": 2
            },
            "details": "Cut out alert",
            "lookup": {}
          },
          "critical_battery": {
            "info": {
              "tagType": "enum",
              "name": "critical_battery",
              "id": 3
            },
            "details": "Critical battery alert",
            "lookup": {}
          },
          "low_battery": {
            "info": {
              "tagType": "enum",
              "name": "low_battery",
              "id": 4
            },
            "details": "Low battery alert",
            "lookup": {}
          },
          "lookup": {
            "0": "none",
            "1": "user",
            "2": "cut_out",
            "3": "critical_battery",
            "4": "low_battery"
          },
          "value": null
        },
        "lookup": {
          "0": "state"
        }
      },
      "AutoTakeOffModeChanged": {
        "info": {
          "tagType": "cmd",
          "name": "AutoTakeOffModeChanged",
          "id": 3
        },
        "details": "Set MiniDrone automatic take off mode",
        "state": {
          "info": {
            "tagType": "arg",
            "name": "state",
            "type": "u8",
            "id": 0,
            "bytes": 1
          },
          "details": "State of automatic take off mode",
          "lookup": {},
          "value": null
        },
        "lookup": {
          "0": "state"
        }
      },
      "FlyingModeChanged": {
        "info": {
          "tagType": "cmd",
          "name": "FlyingModeChanged",
          "id": 4
        },
        "details": "FlyingMode changed. Only supported by WingX",
        "mode": {
          "info": {
            "tagType": "arg",
            "name": "mode",
            "type": "u8",
            "id": 0,
            "bytes": 1
          },
          "details": "Drone Flying Mode",
          "quadricopter": {
            "info": {
              "tagType": "enum",
              "name": "quadricopter",
              "id": 0
            },
            "details": "Fly as a quadrictopter",
            "lookup": {}
          },
          "plane_forward": {
            "info": {
              "tagType": "enum",
              "name": "plane_forward",
              "id": 1
            },
            "details": "Fly as a plane in forward mode",
            "lookup": {}
          },
          "plane_backward": {
            "info": {
              "tagType": "enum",
              "name": "plane_backward",
              "id": 2
            },
            "details": "Fly as a plane in backward mode",
            "lookup": {}
          },
          "lookup": {
            "0": "quadricopter",
            "1": "plane_forward",
            "2": "plane_backward"
          },
          "value": null
        },
        "lookup": {
          "0": "mode"
        }
      },
      "PlaneGearBoxChanged": {
        "info": {
          "tagType": "cmd",
          "name": "PlaneGearBoxChanged",
          "id": 5
        },
        "details": "Plane Gear Box changed. Only supported by WingX",
        "state": {
          "info": {
            "tagType": "arg",
            "name": "state",
            "type": "enum",
            "id": 0,
            "bytes": 4
          },
          "details": "Plane Gear Box",
          "gear_1": {
            "info": {
              "tagType": "enum",
              "name": "gear_1",
              "id": 0
            },
            "details": "Gear 1. Low speed",
            "lookup": {}
          },
          "gear_2": {
            "info": {
              "tagType": "enum",
              "name": "gear_2",
              "id": 1
            },
            "details": "Gear 2. Middle speed",
            "lookup": {}
          },
          "gear_3": {
            "info": {
              "tagType": "enum",
              "name": "gear_3",
              "id": 2
            },
            "details": "Gear 3. High speed",
            "lookup": {}
          },
          "lookup": {
            "0": "gear_1",
            "1": "gear_2",
            "2": "gear_3"
          },
          "value": null
        },
        "lookup": {
          "0": "state"
        }
      },
      "lookup": {
        "0": "FlatTrimChanged",
        "1": "FlyingStateChanged",
        "2": "AlertStateChanged",
        "3": "AutoTakeOffModeChanged",
        "4": "FlyingModeChanged",
        "5": "PlaneGearBoxChanged"
      }
    },
    "Animations": {
      "info": {
        "tagType": "class",
        "name": "Animations",
        "id": 4
      },
      "details": "Animation commands",
      "Flip": {
        "info": {
          "tagType": "cmd",
          "name": "Flip",
          "id": 0
        },
        "details": "Make a flip",
        "direction": {
          "info": {
            "tagType": "arg",
            "name": "direction",
            "type": "enum",
            "id": 0,
            "bytes": 4
          },
          "details": "Direction for the flip",
          "front": {
            "info": {
              "tagType": "enum",
              "name": "front",
              "id": 0
            },
            "details": "Flip direction front",
            "lookup": {}
          },
          "back": {
            "info": {
              "tagType": "enum",
              "name": "back",
              "id": 1
            },
            "details": "Flip direction back",
            "lookup": {}
          },
          "right": {
            "info": {
              "tagType": "enum",
              "name": "right",
              "id": 2
            },
            "details": "Flip direction right",
            "lookup": {}
          },
          "left": {
            "info": {
              "tagType": "enum",
              "name": "left",
              "id": 3
            },
            "details": "Flip direction left",
            "lookup": {}
          },
          "lookup": {
            "0": "front",
            "1": "back",
            "2": "right",
            "3": "left"
          },
          "value": null
        },
        "lookup": {
          "0": "direction"
        }
      },
      "Cap": {
        "info": {
          "tagType": "cmd",
          "name": "Cap",
          "id": 1
        },
        "details": "Change the product cap",
        "offset": {
          "info": {
            "tagType": "arg",
            "name": "offset",
            "type": "i16",
            "id": 0,
            "bytes": 2
          },
          "details": "Change the cap with offset angle [_180;180]",
          "lookup": {},
          "value": null
        },
        "lookup": {
          "0": "offset"
        }
      },
      "lookup": {
        "0": "Flip",
        "1": "Cap"
      }
    },
    "MediaRecord": {
      "info": {
        "tagType": "class",
        "name": "MediaRecord",
        "id": 6
      },
      "details": "Media recording management",
      "Picture": {
        "info": {
          "tagType": "cmd",
          "name": "Picture",
          "id": 0
        },
        "details": "@deprecated Take picture",
        "mass_storage_id": {
          "info": {
            "tagType": "arg",
            "name": "mass_storage_id",
            "type": "u8",
            "id": 0,
            "bytes": 1
          },
          "details": "Mass storage id to take picture",
          "lookup": {},
          "value": null
        },
        "lookup": {
          "0": "mass_storage_id"
        }
      },
      "PictureV2": {
        "info": {
          "tagType": "cmd",
          "name": "PictureV2",
          "id": 1
        },
        "details": "Take picture",
        "lookup": {}
      },
      "lookup": {
        "0": "Picture",
        "1": "PictureV2"
      }
    },
    "MediaRecordState": {
      "info": {
        "tagType": "class",
        "name": "MediaRecordState",
        "id": 7
      },
      "details": "State of media recording",
      "PictureStateChanged": {
        "info": {
          "tagType": "cmd",
          "name": "PictureStateChanged",
          "id": 0
        },
        "details": "@deprecated State of picture recording",
        "state": {
          "info": {
            "tagType": "arg",
            "name": "state",
            "type": "u8",
            "id": 0,
            "bytes": 1
          },
          "details": "1 if picture has been taken, 0 otherwise",
          "lookup": {},
          "value": null
        },
        "mass_storage_id": {
          "info": {
            "tagType": "arg",
            "name": "mass_storage_id",
            "type": "u8",
            "id": 1,
            "bytes": 1
          },
          "details": "Mass storage id to record",
          "lookup": {},
          "value": null
        },
        "lookup": {
          "0": "state",
          "1": "mass_storage_id"
        }
      },
      "PictureStateChangedV2": {
        "info": {
          "tagType": "cmd",
          "name": "PictureStateChangedV2",
          "id": 1
        },
        "details": "State of device picture recording changed",
        "state": {
          "info": {
            "tagType": "arg",
            "name": "state",
            "type": "enum",
            "id": 0,
            "bytes": 4
          },
          "details": "State of device picture recording",
          "ready": {
            "info": {
              "tagType": "enum",
              "name": "ready",
              "id": 0
            },
            "details": "The picture recording is ready",
            "lookup": {}
          },
          "busy": {
            "info": {
              "tagType": "enum",
              "name": "busy",
              "id": 1
            },
            "details": "The picture recording is busy",
            "lookup": {}
          },
          "notAvailable": {
            "info": {
              "tagType": "enum",
              "name": "notAvailable",
              "id": 2
            },
            "details": "The picture recording is not available",
            "lookup": {}
          },
          "lookup": {
            "0": "ready",
            "1": "busy",
            "2": "notAvailable"
          },
          "value": null
        },
        "error": {
          "info": {
            "tagType": "arg",
            "name": "error",
            "type": "enum",
            "id": 1,
            "bytes": 4
          },
          "details": "Error to explain the state",
          "ok": {
            "info": {
              "tagType": "enum",
              "name": "ok",
              "id": 0
            },
            "details": "No Error",
            "lookup": {}
          },
          "unknown": {
            "info": {
              "tagType": "enum",
              "name": "unknown",
              "id": 1
            },
            "details": "Unknown generic error",
            "lookup": {}
          },
          "camera_ko": {
            "info": {
              "tagType": "enum",
              "name": "camera_ko",
              "id": 2
            },
            "details": "Picture camera is out of order",
            "lookup": {}
          },
          "memoryFull": {
            "info": {
              "tagType": "enum",
              "name": "memoryFull",
              "id": 3
            },
            "details": "Memory full ; cannot save one additional picture",
            "lookup": {}
          },
          "lowBattery": {
            "info": {
              "tagType": "enum",
              "name": "lowBattery",
              "id": 4
            },
            "details": "Battery is too low to start/keep recording.",
            "lookup": {}
          },
          "lookup": {
            "0": "ok",
            "1": "unknown",
            "2": "camera_ko",
            "3": "memoryFull",
            "4": "lowBattery"
          },
          "value": null
        },
        "lookup": {
          "0": "state",
          "1": "error"
        }
      },
      "lookup": {
        "0": "PictureStateChanged",
        "1": "PictureStateChangedV2"
      }
    },
    "MediaRecordEvent": {
      "info": {
        "tagType": "class",
        "name": "MediaRecordEvent",
        "id": 2
      },
      "details": "Events of media recording",
      "PictureEventChanged": {
        "info": {
          "tagType": "cmd",
          "name": "PictureEventChanged",
          "id": 0,
          "content": "NOTIFICATION"
        },
        "details": "Event of picture recording",
        "event": {
          "info": {
            "tagType": "arg",
            "name": "event",
            "type": "enum",
            "id": 0,
            "bytes": 4
          },
          "details": "Last event of picture recording",
          "taken": {
            "info": {
              "tagType": "enum",
              "name": "taken",
              "id": 0
            },
            "details": "Picture taken and saved",
            "lookup": {}
          },
          "failed": {
            "info": {
              "tagType": "enum",
              "name": "failed",
              "id": 1
            },
            "details": "Picture failed",
            "lookup": {}
          },
          "lookup": {
            "0": "taken",
            "1": "failed"
          },
          "value": null
        },
        "error": {
          "info": {
            "tagType": "arg",
            "name": "error",
            "type": "enum",
            "id": 1,
            "bytes": 4
          },
          "details": "Error to explain the event",
          "ok": {
            "info": {
              "tagType": "enum",
              "name": "ok",
              "id": 0
            },
            "details": "No Error",
            "lookup": {}
          },
          "unknown": {
            "info": {
              "tagType": "enum",
              "name": "unknown",
              "id": 1
            },
            "details": "Unknown generic error ; only when state is failed",
            "lookup": {}
          },
          "busy": {
            "info": {
              "tagType": "enum",
              "name": "busy",
              "id": 2
            },
            "details": "Picture recording is busy ; only when state is failed",
            "lookup": {}
          },
          "notAvailable": {
            "info": {
              "tagType": "enum",
              "name": "notAvailable",
              "id": 3
            },
            "details": "Picture recording not available ; only when state is failed",
            "lookup": {}
          },
          "memoryFull": {
            "info": {
              "tagType": "enum",
              "name": "memoryFull",
              "id": 4
            },
            "details": "Memory full ; only when state is failed",
            "lookup": {}
          },
          "lowBattery": {
            "info": {
              "tagType": "enum",
              "name": "lowBattery",
              "id": 5
            },
            "details": "Battery is too low to record.",
            "lookup": {}
          },
          "lookup": {
            "0": "ok",
            "1": "unknown",
            "2": "busy",
            "3": "notAvailable",
            "4": "memoryFull",
            "5": "lowBattery"
          },
          "value": null
        },
        "lookup": {
          "0": "event",
          "1": "error"
        }
      },
      "lookup": {
        "0": "PictureEventChanged"
      }
    },
    "PilotingSettings": {
      "info": {
        "tagType": "class",
        "name": "PilotingSettings",
        "id": 8
      },
      "details": "Piloting Settings commands",
      "MaxAltitude": {
        "info": {
          "tagType": "cmd",
          "name": "MaxAltitude",
          "id": 0
        },
        "details": "Set Max Altitude",
        "current": {
          "info": {
            "tagType": "arg",
            "name": "current",
            "type": "float",
            "id": 0,
            "bytes": 4
          },
          "details": "Current altitude max in m",
          "lookup": {},
          "value": null
        },
        "lookup": {
          "0": "current"
        }
      },
      "MaxTilt": {
        "info": {
          "tagType": "cmd",
          "name": "MaxTilt",
          "id": 1
        },
        "details": "Set Max Tilt",
        "current": {
          "info": {
            "tagType": "arg",
            "name": "current",
            "type": "float",
            "id": 0,
            "bytes": 4
          },
          "details": "Current tilt max in degree",
          "lookup": {},
          "value": null
        },
        "lookup": {
          "0": "current"
        }
      },
      "BankedTurn": {
        "info": {
          "tagType": "cmd",
          "name": "BankedTurn",
          "id": 2
        },
        "comment": {
          "info": {
            "title": "Set banked turn mode",
            "desc": "Set banked turn mode.\\n When banked turn mode is enabled, the drone will use yaw values from the piloting command to infer with roll and pitch on the drone when its horizontal speed is not null.",
            "support": "none",
            "result": "The banked turn mode is enabled or disabled.\\n Then, event [BankedTurnMode](#2_9_2) is triggered."
          }
        },
        "value": {
          "info": {
            "tagType": "arg",
            "name": "value",
            "type": "u8",
            "id": 0,
            "bytes": 1
          },
          "details": "1 to enable, 0 to disable",
          "lookup": {},
          "value": null
        },
        "lookup": {
          "0": "value"
        }
      },
      "lookup": {
        "0": "MaxAltitude",
        "1": "MaxTilt",
        "2": "BankedTurn"
      }
    },
    "PilotingSettingsState": {
      "info": {
        "tagType": "class",
        "name": "PilotingSettingsState",
        "id": 9
      },
      "details": "Piloting Settings state from product",
      "MaxAltitudeChanged": {
        "info": {
          "tagType": "cmd",
          "name": "MaxAltitudeChanged",
          "id": 0
        },
        "details": "Max Altitude sent by product",
        "current": {
          "info": {
            "tagType": "arg",
            "name": "current",
            "type": "float",
            "id": 0,
            "bytes": 4
          },
          "details": "Current altitude max",
          "lookup": {},
          "value": null
        },
        "min": {
          "info": {
            "tagType": "arg",
            "name": "min",
            "type": "float",
            "id": 1,
            "bytes": 4
          },
          "details": "Range min of altitude",
          "lookup": {},
          "value": null
        },
        "max": {
          "info": {
            "tagType": "arg",
            "name": "max",
            "type": "float",
            "id": 2,
            "bytes": 4
          },
          "details": "Range max of altitude",
          "lookup": {},
          "value": null
        },
        "lookup": {
          "0": "current",
          "1": "min",
          "2": "max"
        }
      },
      "MaxTiltChanged": {
        "info": {
          "tagType": "cmd",
          "name": "MaxTiltChanged",
          "id": 1
        },
        "details": "Max tilt sent by product",
        "current": {
          "info": {
            "tagType": "arg",
            "name": "current",
            "type": "float",
            "id": 0,
            "bytes": 4
          },
          "details": "Current max tilt",
          "lookup": {},
          "value": null
        },
        "min": {
          "info": {
            "tagType": "arg",
            "name": "min",
            "type": "float",
            "id": 1,
            "bytes": 4
          },
          "details": "Range min of tilt",
          "lookup": {},
          "value": null
        },
        "max": {
          "info": {
            "tagType": "arg",
            "name": "max",
            "type": "float",
            "id": 2,
            "bytes": 4
          },
          "details": "Range max of tilt",
          "lookup": {},
          "value": null
        },
        "lookup": {
          "0": "current",
          "1": "min",
          "2": "max"
        }
      },
      "BankedTurnChanged": {
        "info": {
          "tagType": "cmd",
          "name": "BankedTurnChanged",
          "id": 2
        },
        "comment": {
          "info": {
            "title": "Banked Turn mode",
            "desc": "Banked Turn mode.\\n If banked turn mode is enabled, the drone will use yaw values from the piloting command to infer with roll and pitch on the drone when its horizontal speed is not null.",
            "support": "none",
            "triggered": "by [SetBankedTurnMode](#2_8_2)."
          }
        },
        "state": {
          "info": {
            "tagType": "arg",
            "name": "state",
            "type": "u8",
            "id": 0,
            "bytes": 1
          },
          "details": "1 if enabled, 0 if disabled",
          "lookup": {},
          "value": null
        },
        "lookup": {
          "0": "state"
        }
      },
      "lookup": {
        "0": "MaxAltitudeChanged",
        "1": "MaxTiltChanged",
        "2": "BankedTurnChanged"
      }
    },
    "SpeedSettings": {
      "info": {
        "tagType": "class",
        "name": "SpeedSettings",
        "id": 1
      },
      "details": "Speed Settings commands",
      "MaxVerticalSpeed": {
        "info": {
          "tagType": "cmd",
          "name": "MaxVerticalSpeed",
          "id": 0
        },
        "details": "Set Max Vertical speed",
        "current": {
          "info": {
            "tagType": "arg",
            "name": "current",
            "type": "float",
            "id": 0,
            "bytes": 4
          },
          "details": "Current max vertical speed in m/s",
          "lookup": {},
          "value": null
        },
        "lookup": {
          "0": "current"
        }
      },
      "MaxRotationSpeed": {
        "info": {
          "tagType": "cmd",
          "name": "MaxRotationSpeed",
          "id": 1
        },
        "details": "Set Max Rotation speed",
        "current": {
          "info": {
            "tagType": "arg",
            "name": "current",
            "type": "float",
            "id": 0,
            "bytes": 4
          },
          "details": "Current max rotation speed in degree/s",
          "lookup": {},
          "value": null
        },
        "lookup": {
          "0": "current"
        }
      },
      "Wheels": {
        "info": {
          "tagType": "cmd",
          "name": "Wheels",
          "id": 2
        },
        "details": "Presence of wheels",
        "present": {
          "info": {
            "tagType": "arg",
            "name": "present",
            "type": "u8",
            "id": 0,
            "bytes": 1
          },
          "details": "1 if present, 0 if not present",
          "lookup": {},
          "value": null
        },
        "lookup": {
          "0": "present"
        }
      },
      "MaxHorizontalSpeed": {
        "info": {
          "tagType": "cmd",
          "name": "MaxHorizontalSpeed",
          "id": 3
        },
        "details": "Set Max Horizontal speed (only used in case where PilotingSettings_MaxTilt is not used like in hydrofoil mode)",
        "current": {
          "info": {
            "tagType": "arg",
            "name": "current",
            "type": "float",
            "id": 0,
            "bytes": 4
          },
          "details": "Current max Horizontal speed in m/s",
          "lookup": {},
          "value": null
        },
        "lookup": {
          "0": "current"
        }
      },
      "MaxPlaneModeRotationSpeed": {
        "info": {
          "tagType": "cmd",
          "name": "MaxPlaneModeRotationSpeed",
          "id": 4
        },
        "details": "Set max plane mode rotation speed (only available for wing x)",
        "current": {
          "info": {
            "tagType": "arg",
            "name": "current",
            "type": "float",
            "id": 0,
            "bytes": 4
          },
          "details": "Current max plane mode rotation speed in degree/s",
          "lookup": {},
          "value": null
        },
        "lookup": {
          "0": "current"
        }
      },
      "lookup": {
        "0": "MaxVerticalSpeed",
        "1": "MaxRotationSpeed",
        "2": "Wheels",
        "3": "MaxHorizontalSpeed",
        "4": "MaxPlaneModeRotationSpeed"
      }
    },
    "SpeedSettingsState": {
      "info": {
        "tagType": "class",
        "name": "SpeedSettingsState",
        "id": 5
      },
      "details": "Speed Settings state from product",
      "MaxVerticalSpeedChanged": {
        "info": {
          "tagType": "cmd",
          "name": "MaxVerticalSpeedChanged",
          "id": 0
        },
        "details": "Max vertical speed sent by product",
        "current": {
          "info": {
            "tagType": "arg",
            "name": "current",
            "type": "float",
            "id": 0,
            "bytes": 4
          },
          "details": "Current max vertical speed in m/s",
          "lookup": {},
          "value": null
        },
        "min": {
          "info": {
            "tagType": "arg",
            "name": "min",
            "type": "float",
            "id": 1,
            "bytes": 4
          },
          "details": "Range min of vertical speed",
          "lookup": {},
          "value": null
        },
        "max": {
          "info": {
            "tagType": "arg",
            "name": "max",
            "type": "float",
            "id": 2,
            "bytes": 4
          },
          "details": "Range max of vertical speed",
          "lookup": {},
          "value": null
        },
        "lookup": {
          "0": "current",
          "1": "min",
          "2": "max"
        }
      },
      "MaxRotationSpeedChanged": {
        "info": {
          "tagType": "cmd",
          "name": "MaxRotationSpeedChanged",
          "id": 1
        },
        "details": "Max rotation speed sent by product",
        "current": {
          "info": {
            "tagType": "arg",
            "name": "current",
            "type": "float",
            "id": 0,
            "bytes": 4
          },
          "details": "Current max rotation speed in degree/s",
          "lookup": {},
          "value": null
        },
        "min": {
          "info": {
            "tagType": "arg",
            "name": "min",
            "type": "float",
            "id": 1,
            "bytes": 4
          },
          "details": "Range min of rotation speed",
          "lookup": {},
          "value": null
        },
        "max": {
          "info": {
            "tagType": "arg",
            "name": "max",
            "type": "float",
            "id": 2,
            "bytes": 4
          },
          "details": "Range max of rotation speed",
          "lookup": {},
          "value": null
        },
        "lookup": {
          "0": "current",
          "1": "min",
          "2": "max"
        }
      },
      "WheelsChanged": {
        "info": {
          "tagType": "cmd",
          "name": "WheelsChanged",
          "id": 2
        },
        "details": "Presence of wheels sent by product",
        "present": {
          "info": {
            "tagType": "arg",
            "name": "present",
            "type": "u8",
            "id": 0,
            "bytes": 1
          },
          "details": "1 if present, 0 if not present",
          "lookup": {},
          "value": null
        },
        "lookup": {
          "0": "present"
        }
      },
      "MaxHorizontalSpeedChanged": {
        "info": {
          "tagType": "cmd",
          "name": "MaxHorizontalSpeedChanged",
          "id": 3
        },
        "details": "Max horizontal speed sent by product (only used in case where PilotingSettings_MaxTilt is not used like in hydrofoil mode)",
        "current": {
          "info": {
            "tagType": "arg",
            "name": "current",
            "type": "float",
            "id": 0,
            "bytes": 4
          },
          "details": "Current max horizontal speed in m/s",
          "lookup": {},
          "value": null
        },
        "min": {
          "info": {
            "tagType": "arg",
            "name": "min",
            "type": "float",
            "id": 1,
            "bytes": 4
          },
          "details": "Range min of horizontal speed",
          "lookup": {},
          "value": null
        },
        "max": {
          "info": {
            "tagType": "arg",
            "name": "max",
            "type": "float",
            "id": 2,
            "bytes": 4
          },
          "details": "Range max of horizontal speed",
          "lookup": {},
          "value": null
        },
        "lookup": {
          "0": "current",
          "1": "min",
          "2": "max"
        }
      },
      "MaxPlaneModeRotationSpeedChanged": {
        "info": {
          "tagType": "cmd",
          "name": "MaxPlaneModeRotationSpeedChanged",
          "id": 4
        },
        "details": "Max plane rotation speed sent by product (only available for wing x)",
        "current": {
          "info": {
            "tagType": "arg",
            "name": "current",
            "type": "float",
            "id": 0,
            "bytes": 4
          },
          "details": "Current max plane mode rotation speed in degree/s",
          "lookup": {},
          "value": null
        },
        "min": {
          "info": {
            "tagType": "arg",
            "name": "min",
            "type": "float",
            "id": 1,
            "bytes": 4
          },
          "details": "Range min of plane mode rotation speed",
          "lookup": {},
          "value": null
        },
        "max": {
          "info": {
            "tagType": "arg",
            "name": "max",
            "type": "float",
            "id": 2,
            "bytes": 4
          },
          "details": "Range max of plane mode rotation speed",
          "lookup": {},
          "value": null
        },
        "lookup": {
          "0": "current",
          "1": "min",
          "2": "max"
        }
      },
      "lookup": {
        "0": "MaxVerticalSpeedChanged",
        "1": "MaxRotationSpeedChanged",
        "2": "WheelsChanged",
        "3": "MaxHorizontalSpeedChanged",
        "4": "MaxPlaneModeRotationSpeedChanged"
      }
    },
    "Settings": {
      "info": {
        "tagType": "class",
        "name": "Settings",
        "id": 10
      },
      "details": "Settings commands",
      "CutOutMode": {
        "info": {
          "tagType": "cmd",
          "name": "CutOutMode",
          "id": 0
        },
        "details": "Set MiniDrone cut out mode",
        "enable": {
          "info": {
            "tagType": "arg",
            "name": "enable",
            "type": "u8",
            "id": 0,
            "bytes": 1
          },
          "details": "Enable cut out mode (1 if is activate, 0 otherwise)",
          "lookup": {},
          "value": null
        },
        "lookup": {
          "0": "enable"
        }
      },
      "lookup": {
        "0": "CutOutMode"
      }
    },
    "SettingsState": {
      "info": {
        "tagType": "class",
        "name": "SettingsState",
        "id": 11
      },
      "details": "Settings state from product",
      "ProductMotorsVersionChanged": {
        "info": {
          "tagType": "cmd",
          "name": "ProductMotorsVersionChanged",
          "id": 0
        },
        "details": "@deprecated Product Motors versions",
        "motor": {
          "info": {
            "tagType": "arg",
            "name": "motor",
            "type": "u8",
            "id": 0,
            "bytes": 1
          },
          "details": "Product Motor number [1 _ 4]",
          "lookup": {},
          "value": null
        },
        "type": {
          "info": {
            "tagType": "arg",
            "name": "type",
            "type": "string",
            "id": 1,
            "bytes": 1
          },
          "details": "Product Motor type",
          "lookup": {},
          "value": null
        },
        "software": {
          "info": {
            "tagType": "arg",
            "name": "software",
            "type": "string",
            "id": 2,
            "bytes": 1
          },
          "details": "Product Motors software version",
          "lookup": {},
          "value": null
        },
        "hardware": {
          "info": {
            "tagType": "arg",
            "name": "hardware",
            "type": "string",
            "id": 3,
            "bytes": 1
          },
          "details": "Product Motors hardware version",
          "lookup": {},
          "value": null
        },
        "lookup": {
          "0": "motor",
          "1": "type",
          "2": "software",
          "3": "hardware"
        }
      },
      "ProductInertialVersionChanged": {
        "info": {
          "tagType": "cmd",
          "name": "ProductInertialVersionChanged",
          "id": 1
        },
        "details": "@deprecated Product Inertial versions",
        "software": {
          "info": {
            "tagType": "arg",
            "name": "software",
            "type": "string",
            "id": 0,
            "bytes": 1
          },
          "details": "Product Inertial software version",
          "lookup": {},
          "value": null
        },
        "hardware": {
          "info": {
            "tagType": "arg",
            "name": "hardware",
            "type": "string",
            "id": 1,
            "bytes": 1
          },
          "details": "Product Inertial hardware version",
          "lookup": {},
          "value": null
        },
        "lookup": {
          "0": "software",
          "1": "hardware"
        }
      },
      "CutOutModeChanged": {
        "info": {
          "tagType": "cmd",
          "name": "CutOutModeChanged",
          "id": 2
        },
        "details": "MiniDrone cut out mode",
        "enable": {
          "info": {
            "tagType": "arg",
            "name": "enable",
            "type": "u8",
            "id": 0,
            "bytes": 1
          },
          "details": "State of cut out mode (1 if is activate, 0 otherwise)",
          "lookup": {},
          "value": null
        },
        "lookup": {
          "0": "enable"
        }
      },
      "lookup": {
        "0": "ProductMotorsVersionChanged",
        "1": "ProductInertialVersionChanged",
        "2": "CutOutModeChanged"
      }
    },
    "FloodControlState": {
      "info": {
        "tagType": "class",
        "name": "FloodControlState",
        "id": 12
      },
      "details": "Settings state from product",
      "FloodControlChanged": {
        "info": {
          "tagType": "cmd",
          "name": "FloodControlChanged",
          "id": 0
        },
        "details": "@deprecated Flood control regulation",
        "delay": {
          "info": {
            "tagType": "arg",
            "name": "delay",
            "type": "u16",
            "id": 0,
            "bytes": 2
          },
          "details": "Delay (in ms) between two PCMD",
          "lookup": {},
          "value": null
        },
        "lookup": {
          "0": "delay"
        }
      },
      "lookup": {
        "0": "FloodControlChanged"
      }
    },
    "GPS": {
      "info": {
        "tagType": "class",
        "name": "GPS",
        "id": 13
      },
      "details": "GPS related commands",
      "ControllerLatitudeForRun": {
        "info": {
          "tagType": "cmd",
          "name": "ControllerLatitudeForRun",
          "id": 0
        },
        "details": "Set the controller latitude for a run.",
        "latitude": {
          "info": {
            "tagType": "arg",
            "name": "latitude",
            "type": "double",
            "id": 0,
            "bytes": 1
          },
          "details": "Controller latitude in decimal degrees",
          "lookup": {},
          "value": null
        },
        "lookup": {
          "0": "latitude"
        }
      },
      "ControllerLongitudeForRun": {
        "info": {
          "tagType": "cmd",
          "name": "ControllerLongitudeForRun",
          "id": 1
        },
        "details": "Set the controller longitude for a run.",
        "longitude": {
          "info": {
            "tagType": "arg",
            "name": "longitude",
            "type": "double",
            "id": 0,
            "bytes": 1
          },
          "details": "Controller longitude in decimal degrees",
          "lookup": {},
          "value": null
        },
        "lookup": {
          "0": "longitude"
        }
      },
      "lookup": {
        "0": "ControllerLatitudeForRun",
        "1": "ControllerLongitudeForRun"
      }
    },
    "Configuration": {
      "info": {
        "tagType": "class",
        "name": "Configuration",
        "id": 14
      },
      "details": "Configuration related commands",
      "ControllerType": {
        "info": {
          "tagType": "cmd",
          "name": "ControllerType",
          "id": 0
        },
        "details": "Set the controller type.",
        "type": {
          "info": {
            "tagType": "arg",
            "name": "type",
            "type": "string",
            "id": 0,
            "bytes": 1
          },
          "details": "Controller type like iOS or Android",
          "lookup": {},
          "value": null
        },
        "lookup": {
          "0": "type"
        }
      },
      "ControllerName": {
        "info": {
          "tagType": "cmd",
          "name": "ControllerName",
          "id": 1
        },
        "details": "Set the controller name.",
        "name": {
          "info": {
            "tagType": "arg",
            "name": "name",
            "type": "string",
            "id": 0,
            "bytes": 1
          },
          "details": "Controller name like com.parrot.freeflight3",
          "lookup": {},
          "value": null
        },
        "lookup": {
          "0": "name"
        }
      },
      "lookup": {
        "0": "ControllerType",
        "1": "ControllerName"
      }
    },
    "UsbAccessoryState": {
      "info": {
        "tagType": "class",
        "name": "UsbAccessoryState",
        "id": 15
      },
      "details": "USB Accessories state commands.",
      "LightState": {
        "info": {
          "tagType": "cmd",
          "name": "LightState",
          "id": 0,
          "type": "MAP_ITEM"
        },
        "details": "USB Light accessory state cmd.",
        "id": {
          "info": {
            "tagType": "arg",
            "name": "id",
            "type": "u8",
            "id": 0,
            "bytes": 1
          },
          "details": "Usb accessory id",
          "lookup": {},
          "value": null
        },
        "state": {
          "info": {
            "tagType": "arg",
            "name": "state",
            "type": "enum",
            "id": 1,
            "bytes": 4
          },
          "details": "Usb Light state.",
          "FIXED": {
            "info": {
              "tagType": "enum",
              "name": "FIXED",
              "id": 0
            },
            "details": "Fixed state at given intensity.",
            "lookup": {}
          },
          "BLINKED": {
            "info": {
              "tagType": "enum",
              "name": "BLINKED",
              "id": 1
            },
            "details": "Blinked state.",
            "lookup": {}
          },
          "OSCILLATED": {
            "info": {
              "tagType": "enum",
              "name": "OSCILLATED",
              "id": 2
            },
            "details": "Oscillated state.",
            "lookup": {}
          },
          "lookup": {
            "0": "FIXED",
            "1": "BLINKED",
            "2": "OSCILLATED"
          },
          "value": null
        },
        "intensity": {
          "info": {
            "tagType": "arg",
            "name": "intensity",
            "type": "u8",
            "id": 2,
            "bytes": 1
          },
          "details": "Light intensity from 0 (OFF) to 100 (Max intensity). Only used in FIXED state.",
          "lookup": {},
          "value": null
        },
        "list_flags": {
          "info": {
            "tagType": "arg",
            "name": "list_flags",
            "type": "u8",
            "id": 3,
            "bytes": 1
          },
          "details": "List entry attribute Bitfield. 0x01: First: indicate it's the first element of the list. 0x02: Last: indicate it's the last element of the list. 0x04: Empty: indicate the list is empty (implies First/Last). All other arguments should be ignored. 0x08: Remove: This value should be removed from the existing list.",
          "lookup": {},
          "value": null
        },
        "lookup": {
          "0": "id",
          "1": "state",
          "2": "intensity",
          "3": "list_flags"
        }
      },
      "ClawState": {
        "info": {
          "tagType": "cmd",
          "name": "ClawState",
          "id": 1,
          "type": "MAP_ITEM"
        },
        "details": "USB Claw accessory state cmd.",
        "id": {
          "info": {
            "tagType": "arg",
            "name": "id",
            "type": "u8",
            "id": 0,
            "bytes": 1
          },
          "details": "Usb accessory id",
          "lookup": {},
          "value": null
        },
        "state": {
          "info": {
            "tagType": "arg",
            "name": "state",
            "type": "enum",
            "id": 1,
            "bytes": 4
          },
          "details": "Usb Claw state.",
          "OPENED": {
            "info": {
              "tagType": "enum",
              "name": "OPENED",
              "id": 0
            },
            "details": "Claw is fully opened.",
            "lookup": {}
          },
          "OPENING": {
            "info": {
              "tagType": "enum",
              "name": "OPENING",
              "id": 1
            },
            "details": "Claw open in progress.",
            "lookup": {}
          },
          "CLOSED": {
            "info": {
              "tagType": "enum",
              "name": "CLOSED",
              "id": 2
            },
            "details": "Claw is fully closed.",
            "lookup": {}
          },
          "CLOSING": {
            "info": {
              "tagType": "enum",
              "name": "CLOSING",
              "id": 3
            },
            "details": "Claw close in progress.",
            "lookup": {}
          },
          "lookup": {
            "0": "OPENED",
            "1": "OPENING",
            "2": "CLOSED",
            "3": "CLOSING"
          },
          "value": null
        },
        "list_flags": {
          "info": {
            "tagType": "arg",
            "name": "list_flags",
            "type": "u8",
            "id": 2,
            "bytes": 1
          },
          "details": "List entry attribute Bitfield. 0x01: First: indicate it's the first element of the list. 0x02: Last: indicate it's the last element of the list. 0x04: Empty: indicate the list is empty (implies First/Last). All other arguments should be ignored. 0x08: Remove: This value should be removed from the existing list.",
          "lookup": {},
          "value": null
        },
        "lookup": {
          "0": "id",
          "1": "state",
          "2": "list_flags"
        }
      },
      "GunState": {
        "info": {
          "tagType": "cmd",
          "name": "GunState",
          "id": 2,
          "type": "MAP_ITEM"
        },
        "details": "USB Gun accessory state cmd.",
        "id": {
          "info": {
            "tagType": "arg",
            "name": "id",
            "type": "u8",
            "id": 0,
            "bytes": 1
          },
          "details": "Usb accessory id.",
          "lookup": {},
          "value": null
        },
        "state": {
          "info": {
            "tagType": "arg",
            "name": "state",
            "type": "enum",
            "id": 1,
            "bytes": 4
          },
          "details": "USB Claw state.",
          "READY": {
            "info": {
              "tagType": "enum",
              "name": "READY",
              "id": 0
            },
            "details": "Gun is ready to fire.",
            "lookup": {}
          },
          "BUSY": {
            "info": {
              "tagType": "enum",
              "name": "BUSY",
              "id": 1
            },
            "details": "Gun is busy (ie not ready to fire).",
            "lookup": {}
          },
          "lookup": {
            "0": "READY",
            "1": "BUSY"
          },
          "value": null
        },
        "list_flags": {
          "info": {
            "tagType": "arg",
            "name": "list_flags",
            "type": "u8",
            "id": 2,
            "bytes": 1
          },
          "details": "List entry attribute Bitfield. 0x01: First: indicate it's the first element of the list. 0x02: Last: indicate it's the last element of the list. 0x04: Empty: indicate the list is empty (implies First/Last). All other arguments should be ignored. 0x08: Remove: This value should be removed from the existing list.",
          "lookup": {},
          "value": null
        },
        "lookup": {
          "0": "id",
          "1": "state",
          "2": "list_flags"
        }
      },
      "lookup": {
        "0": "LightState",
        "1": "ClawState",
        "2": "GunState"
      }
    },
    "UsbAccessory": {
      "info": {
        "tagType": "class",
        "name": "UsbAccessory",
        "id": 16
      },
      "details": "USB Accessories control commands.",
      "LightControl": {
        "info": {
          "tagType": "cmd",
          "name": "LightControl",
          "id": 0
        },
        "details": "USB Light control cmd.",
        "id": {
          "info": {
            "tagType": "arg",
            "name": "id",
            "type": "u8",
            "id": 0,
            "bytes": 1
          },
          "details": "Usb accessory id",
          "lookup": {},
          "value": null
        },
        "mode": {
          "info": {
            "tagType": "arg",
            "name": "mode",
            "type": "enum",
            "id": 1,
            "bytes": 4
          },
          "details": "Usb Light mode.",
          "FIXED": {
            "info": {
              "tagType": "enum",
              "name": "FIXED",
              "id": 0
            },
            "details": "Turn light in fixed state at a given intensity.",
            "lookup": {}
          },
          "BLINKED": {
            "info": {
              "tagType": "enum",
              "name": "BLINKED",
              "id": 1
            },
            "details": "Turn light in blinked state.",
            "lookup": {}
          },
          "OSCILLATED": {
            "info": {
              "tagType": "enum",
              "name": "OSCILLATED",
              "id": 2
            },
            "details": "Turn light in oscillated state.",
            "lookup": {}
          },
          "lookup": {
            "0": "FIXED",
            "1": "BLINKED",
            "2": "OSCILLATED"
          },
          "value": null
        },
        "intensity": {
          "info": {
            "tagType": "arg",
            "name": "intensity",
            "type": "u8",
            "id": 2,
            "bytes": 1
          },
          "details": "Light intensity from 0 (OFF) to 100 (Max intensity). Only used in FIXED mode.",
          "lookup": {},
          "value": null
        },
        "lookup": {
          "0": "id",
          "1": "mode",
          "2": "intensity"
        }
      },
      "ClawControl": {
        "info": {
          "tagType": "cmd",
          "name": "ClawControl",
          "id": 1
        },
        "details": "USB Claw control cmd.",
        "id": {
          "info": {
            "tagType": "arg",
            "name": "id",
            "type": "u8",
            "id": 0,
            "bytes": 1
          },
          "details": "Usb accessory id.",
          "lookup": {},
          "value": null
        },
        "action": {
          "info": {
            "tagType": "arg",
            "name": "action",
            "type": "enum",
            "id": 1,
            "bytes": 4
          },
          "details": "USB Claw action.",
          "OPEN": {
            "info": {
              "tagType": "enum",
              "name": "OPEN",
              "id": 0
            },
            "details": "Open Claw.",
            "lookup": {}
          },
          "CLOSE": {
            "info": {
              "tagType": "enum",
              "name": "CLOSE",
              "id": 1
            },
            "details": "Close Claw.",
            "lookup": {}
          },
          "lookup": {
            "0": "OPEN",
            "1": "CLOSE"
          },
          "value": null
        },
        "lookup": {
          "0": "id",
          "1": "action"
        }
      },
      "GunControl": {
        "info": {
          "tagType": "cmd",
          "name": "GunControl",
          "id": 2
        },
        "details": "USB Gun control cmd.",
        "id": {
          "info": {
            "tagType": "arg",
            "name": "id",
            "type": "u8",
            "id": 0,
            "bytes": 1
          },
          "details": "Usb accessory id",
          "lookup": {},
          "value": null
        },
        "action": {
          "info": {
            "tagType": "arg",
            "name": "action",
            "type": "enum",
            "id": 1,
            "bytes": 4
          },
          "details": "USB Gun action.",
          "FIRE": {
            "info": {
              "tagType": "enum",
              "name": "FIRE",
              "id": 0
            },
            "details": "Fire.",
            "lookup": {}
          },
          "lookup": {
            "0": "FIRE"
          },
          "value": null
        },
        "lookup": {
          "0": "id",
          "1": "action"
        }
      },
      "lookup": {
        "0": "LightControl",
        "1": "ClawControl",
        "2": "GunControl"
      }
    },
    "RemoteController": {
      "info": {
        "tagType": "class",
        "name": "RemoteController",
        "id": 17
      },
      "details": "Remote controller related commands.",
      "SetPairedRemote": {
        "info": {
          "tagType": "cmd",
          "name": "SetPairedRemote",
          "id": 0
        },
        "details": "Send the address of the remote controller on which the drone should be paired This is used to pair a Tinos controller Where mac address: MSB_MID_LSB.",
        "msb_mac": {
          "info": {
            "tagType": "arg",
            "name": "msb_mac",
            "type": "u16",
            "id": 0,
            "bytes": 2
          },
          "details": "2 most significant bytes of mac address",
          "lookup": {},
          "value": null
        },
        "mid_mac": {
          "info": {
            "tagType": "arg",
            "name": "mid_mac",
            "type": "u16",
            "id": 1,
            "bytes": 2
          },
          "details": "2 middle bytes of mac address",
          "lookup": {},
          "value": null
        },
        "lsb_mac": {
          "info": {
            "tagType": "arg",
            "name": "lsb_mac",
            "type": "u16",
            "id": 2,
            "bytes": 2
          },
          "details": "2 least significant bytes of mac address",
          "lookup": {},
          "value": null
        },
        "lookup": {
          "0": "msb_mac",
          "1": "mid_mac",
          "2": "lsb_mac"
        }
      },
      "lookup": {
        "0": "SetPairedRemote"
      }
    },
    "NavigationDataState": {
      "info": {
        "tagType": "class",
        "name": "NavigationDataState",
        "id": 18
      },
      "details": "Navigation Data.",
      "DronePosition": {
        "info": {
          "tagType": "cmd",
          "name": "DronePosition",
          "id": 0
        },
        "details": "Get the drone position from takeoff point (0, 0, 0, 0). The orthonormal basis is fixed at this point. The axis are oriented the following way : * X : From the rear of the drone to its front. * Y : From the right of the drone to its left. * Z : Orthogonal to X and Y and oriented upward. * Psi : From 180 to _180 in the clockwise direction,",
        "posx": {
          "info": {
            "tagType": "arg",
            "name": "posx",
            "type": "float",
            "id": 0,
            "bytes": 4
          },
          "details": "Position on X axis, relative to take off position (cm).",
          "lookup": {},
          "value": null
        },
        "posy": {
          "info": {
            "tagType": "arg",
            "name": "posy",
            "type": "float",
            "id": 1,
            "bytes": 4
          },
          "details": "Position on Y axis, relative to take off position (cm).",
          "lookup": {},
          "value": null
        },
        "posz": {
          "info": {
            "tagType": "arg",
            "name": "posz",
            "type": "i16",
            "id": 2,
            "bytes": 2
          },
          "details": "Position on Z axis, relative to take off position (cm).",
          "lookup": {},
          "value": null
        },
        "psi": {
          "info": {
            "tagType": "arg",
            "name": "psi",
            "type": "i16",
            "id": 3,
            "bytes": 2
          },
          "details": "Psi angle [_180; 180], relative to take off orientation.",
          "lookup": {},
          "value": null
        },
        "ts": {
          "info": {
            "tagType": "arg",
            "name": "ts",
            "type": "i16",
            "id": 4,
            "bytes": 2
          },
          "details": "Time elapsed since last data send (ms).",
          "lookup": {},
          "value": null
        },
        "lookup": {
          "0": "posx",
          "1": "posy",
          "2": "posz",
          "3": "psi",
          "4": "ts"
        }
      },
      "lookup": {
        "0": "DronePosition"
      }
    },
    "lookup": {
      "0": "Piloting",
      "1": "SpeedSettings",
      "2": "MediaRecordEvent",
      "3": "PilotingState",
      "4": "Animations",
      "5": "SpeedSettingsState",
      "6": "MediaRecord",
      "7": "MediaRecordState",
      "8": "PilotingSettings",
      "9": "PilotingSettingsState",
      "10": "Settings",
      "11": "SettingsState",
      "12": "FloodControlState",
      "13": "GPS",
      "14": "Configuration",
      "15": "UsbAccessoryState",
      "16": "UsbAccessory",
      "17": "RemoteController",
      "18": "NavigationDataState"
    }
  },
  "lookup": {
    "2": "minidrone"
  }
}

module.exports=projects;
              