ARNETWORKAL_FRAME_TYPE_UNINITIALIZED: 0,
ARNETWORKAL_FRAME_TYPE_ACK: 1,
ARNETWORKAL_FRAME_TYPE_DATA: 2,
ARNETWORKAL_FRAME_TYPE_DATA_LOW_LATENCY: 3,
ARNETWORKAL_FRAME_TYPE_DATA_WITH_ACK: 4,
ARNETWORKAL_FRAME_TYPE_MAX: 5,

ARNETWORKAL_MANAGER_DEFAULT_ID_MAX: 256,
