// eARMEDIA_ENCAPSULER_CODEC
CODEC_UNKNNOWN: 0,
CODEC_VLIB: 1,
CODEC_P264: 2,
CODEC_MPEG4_VISUAL: 3,
CODEC_MPEG4_AVC: 4,
CODEC_MOTION_JPEG: 5,

// eARMEDIA_ENCAPSULER_FRAME_TYPE;
ARMEDIA_ENCAPSULER_FRAME_TYPE_UNKNNOWN: 0,
ARMEDIA_ENCAPSULER_FRAME_TYPE_I_FRAME: 1,
ARMEDIA_ENCAPSULER_FRAME_TYPE_P_FRAME: 2,
ARMEDIA_ENCAPSULER_FRAME_TYPE_JPEG: 3,
ARMEDIA_ENCAPSULER_FRAME_TYPE_MAX: 4,
